// 50-template used vehicle window sticker catalog.
// These are 8.5x11 pre-owned vehicle window sticker definitions.
// They reuse core visual families while supporting OEM themes, dealer themes, passport toggles,
// market transparency, factory-clean API images, CPO rules, and inside/outside placement.

import {
  UsedWindowCPOFocus,
  UsedWindowDealerDifference,
  UsedWindowLuxuryBlack,
  UsedWindowMarketTransparency,
  UsedWindowMinimalCompliance,
  UsedWindowModernPassport,
  UsedWindowOnePrice,
  UsedWindowTraditionalOEM,
} from "./UsedWindowStickerPack";

export type UsedWindowStickerCategory =
  | "core"
  | "pricing"
  | "certification"
  | "dealer_value"
  | "market_transparency"
  | "luxury"
  | "specialty"
  | "oem";

export type UsedWindowStickerFamily =
  | "modern_passport"
  | "traditional_oem"
  | "luxury_black"
  | "cpo_focus"
  | "market_transparency"
  | "one_price"
  | "dealer_difference"
  | "minimal_compliance";

export type UsedWindowStickerTemplateDefinition = {
  id: string;
  name: string;
  category: UsedWindowStickerCategory;
  family: UsedWindowStickerFamily;
  description: string;
  component: typeof UsedWindowModernPassport;
  defaultBadge: string;
  supportsDealerTheme: true;
  supportsOEMTheme: true;
  supportsPassport: boolean;
  supportsMarketTransparency: boolean;
  supportsCPO: boolean;
  supportsFactoryCleanImage: true;
  recommendedImagePreference: "factory_clean_first" | "dealer_photo_first" | "transparent_first";
  recommendedPlacement: "inside_window" | "outside_window" | "either";
  defaultPricingMode:
    | "used_addendum_only"
    | "used_market_value_plus_addendum"
    | "used_live_price_plus_addendum"
    | "passport_live_price_only";
  tags: string[];
  suggestedOEMs?: string[];
};

const core = {
  supportsDealerTheme: true,
  supportsOEMTheme: true,
  supportsFactoryCleanImage: true,
} as const;

export const USED_WINDOW_STICKER_CATALOG_50: UsedWindowStickerTemplateDefinition[] = [
  {
    id: "used-window-core-modern-passport",
    name: "Modern Passport Window Sticker",
    category: "core",
    family: "modern_passport",
    description: "Contemporary 8.5x11 used vehicle sticker with large image, price/value story, passport QR, specs, MPG, market data, and trust source.",
    component: UsedWindowModernPassport,
    defaultBadge: "Used Vehicle Passport",
    ...core,
    supportsPassport: true,
    supportsMarketTransparency: true,
    supportsCPO: true,
    recommendedImagePreference: "factory_clean_first",
    recommendedPlacement: "outside_window",
    defaultPricingMode: "passport_live_price_only",
    tags: ["modern", "passport", "qr", "factory-clean-image"],
  },
  {
    id: "used-window-core-traditional-oem",
    name: "Traditional OEM Window Sticker",
    category: "core",
    family: "traditional_oem",
    description: "Franchise-style pre-owned vehicle sticker with familiar OEM structure, large specs, MPG, vehicle image, and dealer trust module.",
    component: UsedWindowTraditionalOEM,
    defaultBadge: "Used Vehicle Window Sticker",
    ...core,
    supportsPassport: true,
    supportsMarketTransparency: true,
    supportsCPO: true,
    recommendedImagePreference: "factory_clean_first",
    recommendedPlacement: "inside_window",
    defaultPricingMode: "used_market_value_plus_addendum",
    tags: ["traditional", "oem", "franchise", "mpg"],
  },
  {
    id: "used-window-core-traditional-simple",
    name: "Traditional Simple Window Sticker",
    category: "core",
    family: "traditional_oem",
    description: "Simpler OEM-looking used vehicle sticker for dealers that want a conservative layout with fewer digital prompts.",
    component: UsedWindowTraditionalOEM,
    defaultBadge: "Pre-Owned Vehicle",
    ...core,
    supportsPassport: false,
    supportsMarketTransparency: false,
    supportsCPO: false,
    recommendedImagePreference: "factory_clean_first",
    recommendedPlacement: "inside_window",
    defaultPricingMode: "used_live_price_plus_addendum",
    tags: ["traditional", "simple", "no-passport"],
  },
  {
    id: "used-window-core-minimal-compliance",
    name: "Minimal Compliance Window Sticker",
    category: "core",
    family: "minimal_compliance",
    description: "Clean 8.5x11 used vehicle information sticker for high-volume stores that want clarity and quick printing.",
    component: UsedWindowMinimalCompliance,
    defaultBadge: "Used Vehicle Information",
    ...core,
    supportsPassport: true,
    supportsMarketTransparency: false,
    supportsCPO: false,
    recommendedImagePreference: "dealer_photo_first",
    recommendedPlacement: "either",
    defaultPricingMode: "used_live_price_plus_addendum",
    tags: ["minimal", "compliance", "high-volume"],
  },
  {
    id: "used-window-core-minimal-no-qr",
    name: "Minimal No-QR Window Sticker",
    category: "core",
    family: "minimal_compliance",
    description: "Traditional no-passport version for dealers that want a large window sticker without QR or digital passport callouts.",
    component: UsedWindowMinimalCompliance,
    defaultBadge: "Used Vehicle Information",
    ...core,
    supportsPassport: false,
    supportsMarketTransparency: false,
    supportsCPO: false,
    recommendedImagePreference: "factory_clean_first",
    recommendedPlacement: "inside_window",
    defaultPricingMode: "used_live_price_plus_addendum",
    tags: ["minimal", "no-passport", "no-qr"],
  },
  {
    id: "used-window-core-dealer-branded",
    name: "Dealer Branded Window Sticker",
    category: "core",
    family: "dealer_difference",
    description: "Dealer-first layout that emphasizes the store brand, trust source, benefits, clean image, vehicle specs, and optional passport.",
    component: UsedWindowDealerDifference,
    defaultBadge: "Dealer Certified Value",
    ...core,
    supportsPassport: true,
    supportsMarketTransparency: true,
    supportsCPO: true,
    recommendedImagePreference: "factory_clean_first",
    recommendedPlacement: "outside_window",
    defaultPricingMode: "passport_live_price_only",
    tags: ["dealer-brand", "trust", "benefits"],
  },
  {
    id: "used-window-core-image-forward",
    name: "Image Forward Window Sticker",
    category: "core",
    family: "modern_passport",
    description: "Large hero-image version for dealers using factory clean API images or transparent vehicle imagery.",
    component: UsedWindowModernPassport,
    defaultBadge: "Pre-Owned Vehicle",
    ...core,
    supportsPassport: true,
    supportsMarketTransparency: true,
    supportsCPO: true,
    recommendedImagePreference: "transparent_first",
    recommendedPlacement: "outside_window",
    defaultPricingMode: "used_market_value_plus_addendum",
    tags: ["image-forward", "factory-clean", "modern"],
  },
  {
    id: "used-window-core-feature-forward",
    name: "Feature Forward Window Sticker",
    category: "core",
    family: "modern_passport",
    description: "Used window sticker that prioritizes equipment, options, highlights, specs, MPG, and scan engagement.",
    component: UsedWindowModernPassport,
    defaultBadge: "Feature Highlights",
    ...core,
    supportsPassport: true,
    supportsMarketTransparency: false,
    supportsCPO: false,
    recommendedImagePreference: "factory_clean_first",
    recommendedPlacement: "inside_window",
    defaultPricingMode: "used_live_price_plus_addendum",
    tags: ["features", "equipment", "highlights"],
  },
  {
    id: "used-window-core-premium-white",
    name: "Premium White Window Sticker",
    category: "core",
    family: "minimal_compliance",
    description: "Upscale white-space-heavy layout for stores that want premium without dark luxury styling.",
    component: UsedWindowMinimalCompliance,
    defaultBadge: "Premium Pre-Owned",
    ...core,
    supportsPassport: true,
    supportsMarketTransparency: true,
    supportsCPO: true,
    recommendedImagePreference: "factory_clean_first",
    recommendedPlacement: "inside_window",
    defaultPricingMode: "passport_live_price_only",
    tags: ["premium", "white", "clean"],
  },
  {
    id: "used-window-core-passport-optional",
    name: "Passport Optional Window Sticker",
    category: "core",
    family: "modern_passport",
    description: "Base layout designed to render with or without passport modules depending on dealer settings.",
    component: UsedWindowModernPassport,
    defaultBadge: "Used Vehicle Window Sticker",
    ...core,
    supportsPassport: true,
    supportsMarketTransparency: true,
    supportsCPO: true,
    recommendedImagePreference: "factory_clean_first",
    recommendedPlacement: "either",
    defaultPricingMode: "passport_live_price_only",
    tags: ["passport-optional", "rules-based", "modern"],
  },

  {
    id: "used-window-pricing-one-price",
    name: "One Price Window Sticker",
    category: "pricing",
    family: "one_price",
    description: "Large one-price/no-haggle used car sticker with price/value centerpiece, vehicle image, MPG, and passport option.",
    component: UsedWindowOnePrice,
    defaultBadge: "One Price Store",
    ...core,
    supportsPassport: true,
    supportsMarketTransparency: true,
    supportsCPO: false,
    recommendedImagePreference: "factory_clean_first",
    recommendedPlacement: "outside_window",
    defaultPricingMode: "used_live_price_plus_addendum",
    tags: ["one-price", "no-haggle", "price-centerpiece"],
  },
  {
    id: "used-window-pricing-best-price",
    name: "Best Price Window Sticker",
    category: "pricing",
    family: "one_price",
    description: "Built for Best Price and Best Price First stores with live price/passport support.",
    component: UsedWindowOnePrice,
    defaultBadge: "Best Price First",
    ...core,
    supportsPassport: true,
    supportsMarketTransparency: true,
    supportsCPO: false,
    recommendedImagePreference: "factory_clean_first",
    recommendedPlacement: "outside_window",
    defaultPricingMode: "used_live_price_plus_addendum",
    tags: ["best-price", "pricing", "live-price"],
  },
  {
    id: "used-window-pricing-market-value",
    name: "Market Value Window Sticker",
    category: "pricing",
    family: "market_transparency",
    description: "Uses printed market value with live advertised price in the passport, reducing reprint pressure.",
    component: UsedWindowMarketTransparency,
    defaultBadge: "Market Value Verified",
    ...core,
    supportsPassport: true,
    supportsMarketTransparency: true,
    supportsCPO: true,
    recommendedImagePreference: "factory_clean_first",
    recommendedPlacement: "outside_window",
    defaultPricingMode: "used_market_value_plus_addendum",
    tags: ["market-value", "passport-live-price", "low-reprint"],
  },
  {
    id: "used-window-pricing-advertised-price",
    name: "Advertised Price Window Sticker",
    category: "pricing",
    family: "traditional_oem",
    description: "Traditional approach for dealers who want the printed sticker to show the current advertised price.",
    component: UsedWindowTraditionalOEM,
    defaultBadge: "Advertised Price",
    ...core,
    supportsPassport: true,
    supportsMarketTransparency: false,
    supportsCPO: false,
    recommendedImagePreference: "dealer_photo_first",
    recommendedPlacement: "inside_window",
    defaultPricingMode: "used_live_price_plus_addendum",
    tags: ["advertised-price", "traditional", "price"],
  },
  {
    id: "used-window-pricing-passport-live-price",
    name: "Passport Live Price Window Sticker",
    category: "pricing",
    family: "modern_passport",
    description: "Printed sticker is stable while the passport carries current live advertised price and disclosures.",
    component: UsedWindowModernPassport,
    defaultBadge: "Scan For Today's Price",
    ...core,
    supportsPassport: true,
    supportsMarketTransparency: true,
    supportsCPO: true,
    recommendedImagePreference: "factory_clean_first",
    recommendedPlacement: "outside_window",
    defaultPricingMode: "passport_live_price_only",
    tags: ["passport", "live-price", "scan"],
  },
  {
    id: "used-window-pricing-internet-price",
    name: "Internet Price Window Sticker",
    category: "pricing",
    family: "modern_passport",
    description: "Window sticker designed around online pricing strategy and VDP/passport engagement.",
    component: UsedWindowModernPassport,
    defaultBadge: "Internet Price Available",
    ...core,
    supportsPassport: true,
    supportsMarketTransparency: true,
    supportsCPO: false,
    recommendedImagePreference: "factory_clean_first",
    recommendedPlacement: "outside_window",
    defaultPricingMode: "passport_live_price_only",
    tags: ["internet-price", "online", "vdp"],
  },
  {
    id: "used-window-pricing-savings-story",
    name: "Savings Story Window Sticker",
    category: "pricing",
    family: "market_transparency",
    description: "Shows value vs market while letting live price live in the passport.",
    component: UsedWindowMarketTransparency,
    defaultBadge: "Savings Story",
    ...core,
    supportsPassport: true,
    supportsMarketTransparency: true,
    supportsCPO: false,
    recommendedImagePreference: "factory_clean_first",
    recommendedPlacement: "outside_window",
    defaultPricingMode: "used_market_value_plus_addendum",
    tags: ["savings", "market", "value-story"],
  },
  {
    id: "used-window-pricing-value-leader",
    name: "Value Leader Window Sticker",
    category: "pricing",
    family: "dealer_difference",
    description: "Price/value narrative sticker for vehicles positioned as value leaders in the market.",
    component: UsedWindowDealerDifference,
    defaultBadge: "Value Leader",
    ...core,
    supportsPassport: true,
    supportsMarketTransparency: true,
    supportsCPO: false,
    recommendedImagePreference: "factory_clean_first",
    recommendedPlacement: "outside_window",
    defaultPricingMode: "used_market_value_plus_addendum",
    tags: ["value", "dealer-difference", "market"],
  },

  {
    id: "used-window-cert-oem-cpo",
    name: "OEM CPO Window Sticker",
    category: "certification",
    family: "cpo_focus",
    description: "Certification-first 8.5x11 used window sticker for OEM CPO inventory.",
    component: UsedWindowCPOFocus,
    defaultBadge: "OEM Certified Pre-Owned",
    ...core,
    supportsPassport: true,
    supportsMarketTransparency: true,
    supportsCPO: true,
    recommendedImagePreference: "factory_clean_first",
    recommendedPlacement: "inside_window",
    defaultPricingMode: "used_market_value_plus_addendum",
    tags: ["oem-cpo", "certified", "warranty"],
  },
  {
    id: "used-window-cert-dealer-certified",
    name: "Dealer Certified Window Sticker",
    category: "certification",
    family: "cpo_focus",
    description: "Used window sticker for dealer-certified programs and inspection-backed coverage.",
    component: UsedWindowCPOFocus,
    defaultBadge: "Dealer Certified",
    ...core,
    supportsPassport: true,
    supportsMarketTransparency: true,
    supportsCPO: true,
    recommendedImagePreference: "factory_clean_first",
    recommendedPlacement: "either",
    defaultPricingMode: "used_market_value_plus_addendum",
    tags: ["dealer-certified", "inspection", "coverage"],
  },
  {
    id: "used-window-cert-certified-plus",
    name: "Certified Plus Window Sticker",
    category: "certification",
    family: "cpo_focus",
    description: "Certification upgrade sticker for higher tier coverage and finance-upgrade programs.",
    component: UsedWindowCPOFocus,
    defaultBadge: "Certified Plus",
    ...core,
    supportsPassport: true,
    supportsMarketTransparency: true,
    supportsCPO: true,
    recommendedImagePreference: "factory_clean_first",
    recommendedPlacement: "outside_window",
    defaultPricingMode: "passport_live_price_only",
    tags: ["certified-plus", "upgrade", "finance"],
  },
  {
    id: "used-window-cert-warranty-focus",
    name: "Warranty Focus Window Sticker",
    category: "certification",
    family: "cpo_focus",
    description: "Used vehicle sticker that centers included warranty or protection coverage.",
    component: UsedWindowCPOFocus,
    defaultBadge: "Warranty Included",
    ...core,
    supportsPassport: true,
    supportsMarketTransparency: false,
    supportsCPO: true,
    recommendedImagePreference: "factory_clean_first",
    recommendedPlacement: "inside_window",
    defaultPricingMode: "used_addendum_only",
    tags: ["warranty", "coverage", "protection"],
  },
  {
    id: "used-window-cert-inspection-certified",
    name: "Inspection Certified Window Sticker",
    category: "certification",
    family: "cpo_focus",
    description: "Highlights multi-point inspection, service records, and certification eligibility.",
    component: UsedWindowCPOFocus,
    defaultBadge: "Inspection Certified",
    ...core,
    supportsPassport: true,
    supportsMarketTransparency: false,
    supportsCPO: true,
    recommendedImagePreference: "factory_clean_first",
    recommendedPlacement: "inside_window",
    defaultPricingMode: "passport_live_price_only",
    tags: ["inspection", "service-records", "certified"],
  },
  {
    id: "used-window-cert-elite-cpo",
    name: "Elite CPO Window Sticker",
    category: "certification",
    family: "luxury_black",
    description: "Luxury certification sticker for premium certified inventory.",
    component: UsedWindowLuxuryBlack,
    defaultBadge: "Elite Certified",
    ...core,
    supportsPassport: true,
    supportsMarketTransparency: true,
    supportsCPO: true,
    recommendedImagePreference: "transparent_first",
    recommendedPlacement: "inside_window",
    defaultPricingMode: "passport_live_price_only",
    tags: ["elite", "cpo", "luxury"],
  },
  {
    id: "used-window-cert-stair-step-coverage",
    name: "Stair-Step Coverage Window Sticker",
    category: "certification",
    family: "cpo_focus",
    description: "Supports base coverage and optional upgrade tiers, including finance-dependent coverage programs.",
    component: UsedWindowCPOFocus,
    defaultBadge: "Coverage Options",
    ...core,
    supportsPassport: true,
    supportsMarketTransparency: true,
    supportsCPO: true,
    recommendedImagePreference: "factory_clean_first",
    recommendedPlacement: "inside_window",
    defaultPricingMode: "passport_live_price_only",
    tags: ["stair-step", "coverage", "finance-upgrade"],
  },
  {
    id: "used-window-cert-powertrain",
    name: "Powertrain Coverage Window Sticker",
    category: "certification",
    family: "cpo_focus",
    description: "Used window sticker emphasizing powertrain coverage, term, mileage, and inspection confidence.",
    component: UsedWindowCPOFocus,
    defaultBadge: "Powertrain Coverage",
    ...core,
    supportsPassport: true,
    supportsMarketTransparency: false,
    supportsCPO: true,
    recommendedImagePreference: "factory_clean_first",
    recommendedPlacement: "either",
    defaultPricingMode: "used_addendum_only",
    tags: ["powertrain", "coverage", "warranty"],
  },

  {
    id: "used-window-value-dealer-difference",
    name: "Dealer Difference Window Sticker",
    category: "dealer_value",
    family: "dealer_difference",
    description: "Dealer benefit-forward used window sticker with trust score, benefits, image, specs, MPG, and optional market data.",
    component: UsedWindowDealerDifference,
    defaultBadge: "Dealer Difference",
    ...core,
    supportsPassport: true,
    supportsMarketTransparency: true,
    supportsCPO: true,
    recommendedImagePreference: "factory_clean_first",
    recommendedPlacement: "outside_window",
    defaultPricingMode: "passport_live_price_only",
    tags: ["dealer-difference", "benefits", "trust"],
  },
  {
    id: "used-window-value-why-buy-here",
    name: "Why Buy Here Window Sticker",
    category: "dealer_value",
    family: "dealer_difference",
    description: "Explains dealer value props, trust source, benefits, and the passport as the source of truth.",
    component: UsedWindowDealerDifference,
    defaultBadge: "Why Buy Here",
    ...core,
    supportsPassport: true,
    supportsMarketTransparency: true,
    supportsCPO: true,
    recommendedImagePreference: "factory_clean_first",
    recommendedPlacement: "outside_window",
    defaultPricingMode: "passport_live_price_only",
    tags: ["why-buy", "trust", "dealer-brand"],
  },
  {
    id: "used-window-value-lifetime-warranty",
    name: "Lifetime Warranty Window Sticker",
    category: "dealer_value",
    family: "cpo_focus",
    description: "Designed for stores with lifetime powertrain or lifetime warranty offers.",
    component: UsedWindowCPOFocus,
    defaultBadge: "Lifetime Warranty",
    ...core,
    supportsPassport: true,
    supportsMarketTransparency: false,
    supportsCPO: true,
    recommendedImagePreference: "factory_clean_first",
    recommendedPlacement: "outside_window",
    defaultPricingMode: "used_addendum_only",
    tags: ["lifetime-warranty", "powertrain", "coverage"],
  },
  {
    id: "used-window-value-service-records",
    name: "Service Records Window Sticker",
    category: "dealer_value",
    family: "dealer_difference",
    description: "Emphasizes service records, inspection, reconditioning, and maintenance transparency.",
    component: UsedWindowDealerDifference,
    defaultBadge: "Service Records Available",
    ...core,
    supportsPassport: true,
    supportsMarketTransparency: false,
    supportsCPO: false,
    recommendedImagePreference: "dealer_photo_first",
    recommendedPlacement: "inside_window",
    defaultPricingMode: "passport_live_price_only",
    tags: ["service-records", "inspection", "reconditioning"],
  },
  {
    id: "used-window-value-reconditioning",
    name: "Reconditioning Story Window Sticker",
    category: "dealer_value",
    family: "dealer_difference",
    description: "Shows reconditioning, inspection, installed equipment, and ownership benefits.",
    component: UsedWindowDealerDifference,
    defaultBadge: "Reconditioned & Ready",
    ...core,
    supportsPassport: true,
    supportsMarketTransparency: false,
    supportsCPO: true,
    recommendedImagePreference: "dealer_photo_first",
    recommendedPlacement: "inside_window",
    defaultPricingMode: "used_addendum_only",
    tags: ["reconditioning", "service", "inspection"],
  },
  {
    id: "used-window-value-vip-ownership",
    name: "VIP Ownership Window Sticker",
    category: "dealer_value",
    family: "luxury_black",
    description: "Premium sticker for VIP ownership packages, concierge service, and dealer benefits.",
    component: UsedWindowLuxuryBlack,
    defaultBadge: "VIP Ownership",
    ...core,
    supportsPassport: true,
    supportsMarketTransparency: true,
    supportsCPO: true,
    recommendedImagePreference: "transparent_first",
    recommendedPlacement: "inside_window",
    defaultPricingMode: "passport_live_price_only",
    tags: ["vip", "ownership", "luxury"],
  },

  {
    id: "used-window-market-transparency",
    name: "Market Transparency Window Sticker",
    category: "market_transparency",
    family: "market_transparency",
    description: "Market-first used car sticker that establishes value while pushing live sale price into the passport.",
    component: UsedWindowMarketTransparency,
    defaultBadge: "Market Transparency",
    ...core,
    supportsPassport: true,
    supportsMarketTransparency: true,
    supportsCPO: true,
    recommendedImagePreference: "factory_clean_first",
    recommendedPlacement: "outside_window",
    defaultPricingMode: "used_market_value_plus_addendum",
    tags: ["market", "transparency", "live-price"],
  },
  {
    id: "used-window-market-intelligence",
    name: "Market Intelligence Window Sticker",
    category: "market_transparency",
    family: "market_transparency",
    description: "More analytical market data sticker with market average, comps, Black Book story, specs, MPG, and QR.",
    component: UsedWindowMarketTransparency,
    defaultBadge: "Market Intelligence",
    ...core,
    supportsPassport: true,
    supportsMarketTransparency: true,
    supportsCPO: true,
    recommendedImagePreference: "factory_clean_first",
    recommendedPlacement: "inside_window",
    defaultPricingMode: "used_market_value_plus_addendum",
    tags: ["marketcheck", "black-book", "analytics"],
  },
  {
    id: "used-window-market-fair-price",
    name: "Fair Price Window Sticker",
    category: "market_transparency",
    family: "market_transparency",
    description: "Customer-friendly market sticker focused on fair value, comps, trust, and passport scan engagement.",
    component: UsedWindowMarketTransparency,
    defaultBadge: "Fair Price Verified",
    ...core,
    supportsPassport: true,
    supportsMarketTransparency: true,
    supportsCPO: false,
    recommendedImagePreference: "factory_clean_first",
    recommendedPlacement: "outside_window",
    defaultPricingMode: "used_market_value_plus_addendum",
    tags: ["fair-price", "verified", "customer-trust"],
  },
  {
    id: "used-window-market-competitive-comps",
    name: "Competitive Comps Window Sticker",
    category: "market_transparency",
    family: "market_transparency",
    description: "Designed for dealers that want to show comparable count, market position, and price confidence.",
    component: UsedWindowMarketTransparency,
    defaultBadge: "Competitive Comparison",
    ...core,
    supportsPassport: true,
    supportsMarketTransparency: true,
    supportsCPO: false,
    recommendedImagePreference: "factory_clean_first",
    recommendedPlacement: "inside_window",
    defaultPricingMode: "used_market_value_plus_addendum",
    tags: ["comps", "comparison", "market"],
  },
  {
    id: "used-window-market-price-confidence",
    name: "Price Confidence Window Sticker",
    category: "market_transparency",
    family: "market_transparency",
    description: "Simplified market confidence sticker for customers who want a quick value explanation.",
    component: UsedWindowMarketTransparency,
    defaultBadge: "Price Confidence",
    ...core,
    supportsPassport: true,
    supportsMarketTransparency: true,
    supportsCPO: false,
    recommendedImagePreference: "factory_clean_first",
    recommendedPlacement: "outside_window",
    defaultPricingMode: "used_market_value_plus_addendum",
    tags: ["confidence", "trust", "market"],
  },
  {
    id: "used-window-market-passport-truth",
    name: "Passport Truth Window Sticker",
    category: "market_transparency",
    family: "modern_passport",
    description: "Explicit source-of-truth concept: printed value story, live price and full data inside passport.",
    component: UsedWindowModernPassport,
    defaultBadge: "Passport Is Source Of Truth",
    ...core,
    supportsPassport: true,
    supportsMarketTransparency: true,
    supportsCPO: true,
    recommendedImagePreference: "factory_clean_first",
    recommendedPlacement: "outside_window",
    defaultPricingMode: "passport_live_price_only",
    tags: ["passport-truth", "source-of-truth", "live-data"],
  },

  {
    id: "used-window-luxury-executive-black",
    name: "Executive Black Window Sticker",
    category: "luxury",
    family: "luxury_black",
    description: "Luxury 8.5x11 used vehicle sticker for high-line inventory with clean image, premium trust, and passport optionality.",
    component: UsedWindowLuxuryBlack,
    defaultBadge: "Executive Collection",
    ...core,
    supportsPassport: true,
    supportsMarketTransparency: true,
    supportsCPO: true,
    recommendedImagePreference: "transparent_first",
    recommendedPlacement: "inside_window",
    defaultPricingMode: "passport_live_price_only",
    tags: ["luxury", "executive", "black"],
    suggestedOEMs: ["INFINITI", "Lexus", "BMW", "Mercedes-Benz", "Audi", "Cadillac", "Genesis", "Volvo"],
  },
  {
    id: "used-window-luxury-executive-white",
    name: "Executive White Window Sticker",
    category: "luxury",
    family: "minimal_compliance",
    description: "Clean premium white window sticker for luxury stores that do not want heavy dark framing.",
    component: UsedWindowMinimalCompliance,
    defaultBadge: "Executive Pre-Owned",
    ...core,
    supportsPassport: true,
    supportsMarketTransparency: true,
    supportsCPO: true,
    recommendedImagePreference: "factory_clean_first",
    recommendedPlacement: "inside_window",
    defaultPricingMode: "passport_live_price_only",
    tags: ["luxury", "white", "minimal"],
    suggestedOEMs: ["Lexus", "Acura", "Volvo", "Lincoln", "Genesis"],
  },
  {
    id: "used-window-luxury-concierge",
    name: "Luxury Concierge Window Sticker",
    category: "luxury",
    family: "luxury_black",
    description: "Concierge-oriented premium window sticker for high-line dealers and executive inventory.",
    component: UsedWindowLuxuryBlack,
    defaultBadge: "Luxury Concierge",
    ...core,
    supportsPassport: true,
    supportsMarketTransparency: true,
    supportsCPO: true,
    recommendedImagePreference: "transparent_first",
    recommendedPlacement: "inside_window",
    defaultPricingMode: "passport_live_price_only",
    tags: ["concierge", "premium", "high-line"],
    suggestedOEMs: ["Mercedes-Benz", "BMW", "Audi", "Porsche", "Cadillac", "INFINITI"],
  },
  {
    id: "used-window-luxury-signature-collection",
    name: "Signature Collection Window Sticker",
    category: "luxury",
    family: "luxury_black",
    description: "Top-tier luxury sticker for curated premium pre-owned inventory and special collections.",
    component: UsedWindowLuxuryBlack,
    defaultBadge: "Signature Collection",
    ...core,
    supportsPassport: true,
    supportsMarketTransparency: true,
    supportsCPO: true,
    recommendedImagePreference: "transparent_first",
    recommendedPlacement: "outside_window",
    defaultPricingMode: "passport_live_price_only",
    tags: ["signature", "collection", "premium"],
    suggestedOEMs: ["INFINITI", "Lexus", "BMW", "Mercedes-Benz", "Audi", "Genesis", "Cadillac", "Volvo"],
  },

  {
    id: "used-window-specialty-service-loaner",
    name: "Service Loaner Window Sticker",
    category: "specialty",
    family: "traditional_oem",
    description: "OEM-style window sticker for retired service loaners with mileage, service history, image, specs, MPG, and passport.",
    component: UsedWindowTraditionalOEM,
    defaultBadge: "Service Loaner",
    ...core,
    supportsPassport: true,
    supportsMarketTransparency: true,
    supportsCPO: true,
    recommendedImagePreference: "factory_clean_first",
    recommendedPlacement: "inside_window",
    defaultPricingMode: "used_market_value_plus_addendum",
    tags: ["service-loaner", "loaner", "oem"],
  },
  {
    id: "used-window-specialty-demo",
    name: "Demo Vehicle Window Sticker",
    category: "specialty",
    family: "traditional_oem",
    description: "Large used vehicle sticker for demo and executive vehicles with mileage and condition emphasis.",
    component: UsedWindowTraditionalOEM,
    defaultBadge: "Demo Vehicle",
    ...core,
    supportsPassport: true,
    supportsMarketTransparency: true,
    supportsCPO: true,
    recommendedImagePreference: "dealer_photo_first",
    recommendedPlacement: "inside_window",
    defaultPricingMode: "used_market_value_plus_addendum",
    tags: ["demo", "executive", "mileage"],
  },
  {
    id: "used-window-specialty-manager-special",
    name: "Manager Special Window Sticker",
    category: "specialty",
    family: "dealer_difference",
    description: "Promotional used window sticker for manager specials, aged inventory, and spotlight vehicles.",
    component: UsedWindowDealerDifference,
    defaultBadge: "Manager Special",
    ...core,
    supportsPassport: true,
    supportsMarketTransparency: true,
    supportsCPO: false,
    recommendedImagePreference: "factory_clean_first",
    recommendedPlacement: "outside_window",
    defaultPricingMode: "passport_live_price_only",
    tags: ["manager-special", "promotion", "spotlight"],
  },
  {
    id: "used-window-specialty-ev-hybrid",
    name: "EV / Hybrid Window Sticker",
    category: "specialty",
    family: "modern_passport",
    description: "Pre-owned EV/hybrid sticker with efficiency, range/charging highlights, clean image, and passport support.",
    component: UsedWindowModernPassport,
    defaultBadge: "EV / Hybrid Pre-Owned",
    ...core,
    supportsPassport: true,
    supportsMarketTransparency: true,
    supportsCPO: false,
    recommendedImagePreference: "factory_clean_first",
    recommendedPlacement: "inside_window",
    defaultPricingMode: "used_market_value_plus_addendum",
    tags: ["ev", "hybrid", "range", "efficiency"],
  },
  {
    id: "used-window-specialty-commercial-fleet",
    name: "Commercial / Fleet Window Sticker",
    category: "specialty",
    family: "minimal_compliance",
    description: "Durable and direct 8.5x11 sticker for vans, fleet units, commercial trucks, and work vehicles.",
    component: UsedWindowMinimalCompliance,
    defaultBadge: "Commercial Vehicle",
    ...core,
    supportsPassport: false,
    supportsMarketTransparency: false,
    supportsCPO: false,
    recommendedImagePreference: "dealer_photo_first",
    recommendedPlacement: "outside_window",
    defaultPricingMode: "used_addendum_only",
    tags: ["commercial", "fleet", "work-truck", "van"],
  },
  {
    id: "used-window-specialty-truck-suv",
    name: "Truck / SUV Window Sticker",
    category: "specialty",
    family: "dealer_difference",
    description: "Bold truck/SUV used sticker for towing, drivetrain, capability, image, MPG, and dealer value props.",
    component: UsedWindowDealerDifference,
    defaultBadge: "Truck / SUV Ready",
    ...core,
    supportsPassport: true,
    supportsMarketTransparency: true,
    supportsCPO: false,
    recommendedImagePreference: "factory_clean_first",
    recommendedPlacement: "outside_window",
    defaultPricingMode: "used_market_value_plus_addendum",
    tags: ["truck", "suv", "capability", "awd", "4x4"],
  },

  {
    id: "used-window-oem-acura",
    name: "Acura Pre-Owned Window Sticker",
    category: "oem",
    family: "luxury_black",
    description: "Acura-themed used window sticker with premium image, specs, MPG, trust source, and passport option.",
    component: UsedWindowLuxuryBlack,
    defaultBadge: "Acura Pre-Owned",
    ...core,
    supportsPassport: true,
    supportsMarketTransparency: true,
    supportsCPO: true,
    recommendedImagePreference: "factory_clean_first",
    recommendedPlacement: "inside_window",
    defaultPricingMode: "used_market_value_plus_addendum",
    tags: ["acura", "oem", "premium"],
    suggestedOEMs: ["Acura"],
  },
  {
    id: "used-window-oem-audi",
    name: "Audi Pre-Owned Window Sticker",
    category: "oem",
    family: "luxury_black",
    description: "Audi-themed premium used sticker with factory-clean image and passport-first strategy.",
    component: UsedWindowLuxuryBlack,
    defaultBadge: "Audi Pre-Owned",
    ...core,
    supportsPassport: true,
    supportsMarketTransparency: true,
    supportsCPO: true,
    recommendedImagePreference: "transparent_first",
    recommendedPlacement: "inside_window",
    defaultPricingMode: "passport_live_price_only",
    tags: ["audi", "oem", "luxury"],
    suggestedOEMs: ["Audi"],
  },
  {
    id: "used-window-oem-bmw",
    name: "BMW Pre-Owned Window Sticker",
    category: "oem",
    family: "luxury_black",
    description: "BMW-themed used window sticker with premium layout, MPG, image, trust source, and passport support.",
    component: UsedWindowLuxuryBlack,
    defaultBadge: "BMW Pre-Owned",
    ...core,
    supportsPassport: true,
    supportsMarketTransparency: true,
    supportsCPO: true,
    recommendedImagePreference: "transparent_first",
    recommendedPlacement: "inside_window",
    defaultPricingMode: "passport_live_price_only",
    tags: ["bmw", "oem", "luxury"],
    suggestedOEMs: ["BMW"],
  },
  {
    id: "used-window-oem-cadillac",
    name: "Cadillac Pre-Owned Window Sticker",
    category: "oem",
    family: "luxury_black",
    description: "Cadillac-themed high-line used sticker with strong image presence and trust modules.",
    component: UsedWindowLuxuryBlack,
    defaultBadge: "Cadillac Pre-Owned",
    ...core,
    supportsPassport: true,
    supportsMarketTransparency: true,
    supportsCPO: true,
    recommendedImagePreference: "transparent_first",
    recommendedPlacement: "inside_window",
    defaultPricingMode: "used_market_value_plus_addendum",
    tags: ["cadillac", "oem", "luxury"],
    suggestedOEMs: ["Cadillac"],
  },
  {
    id: "used-window-oem-chevrolet",
    name: "Chevrolet Pre-Owned Window Sticker",
    category: "oem",
    family: "traditional_oem",
    description: "Chevrolet-themed OEM-style used vehicle sticker for franchise operations.",
    component: UsedWindowTraditionalOEM,
    defaultBadge: "Chevrolet Pre-Owned",
    ...core,
    supportsPassport: true,
    supportsMarketTransparency: true,
    supportsCPO: true,
    recommendedImagePreference: "factory_clean_first",
    recommendedPlacement: "outside_window",
    defaultPricingMode: "used_market_value_plus_addendum",
    tags: ["chevrolet", "oem", "franchise"],
    suggestedOEMs: ["Chevrolet"],
  },
  {
    id: "used-window-oem-ford",
    name: "Ford Pre-Owned Window Sticker",
    category: "oem",
    family: "traditional_oem",
    description: "Ford-themed used window sticker for Blue Advantage and pre-owned inventory.",
    component: UsedWindowTraditionalOEM,
    defaultBadge: "Ford Pre-Owned",
    ...core,
    supportsPassport: true,
    supportsMarketTransparency: true,
    supportsCPO: true,
    recommendedImagePreference: "factory_clean_first",
    recommendedPlacement: "outside_window",
    defaultPricingMode: "used_market_value_plus_addendum",
    tags: ["ford", "oem", "blue-advantage"],
    suggestedOEMs: ["Ford"],
  },
  {
    id: "used-window-oem-honda",
    name: "Honda Pre-Owned Window Sticker",
    category: "oem",
    family: "traditional_oem",
    description: "Honda-themed used sticker with OEM familiarity, factory image, MPG, and optional passport.",
    component: UsedWindowTraditionalOEM,
    defaultBadge: "Honda Pre-Owned",
    ...core,
    supportsPassport: true,
    supportsMarketTransparency: true,
    supportsCPO: true,
    recommendedImagePreference: "factory_clean_first",
    recommendedPlacement: "inside_window",
    defaultPricingMode: "used_market_value_plus_addendum",
    tags: ["honda", "oem", "hondatrue"],
    suggestedOEMs: ["Honda"],
  },
  {
    id: "used-window-oem-hyundai",
    name: "Hyundai Pre-Owned Window Sticker",
    category: "oem",
    family: "modern_passport",
    description: "Hyundai-themed modern used window sticker with factory-clean image, MPG, and passport support.",
    component: UsedWindowModernPassport,
    defaultBadge: "Hyundai Pre-Owned",
    ...core,
    supportsPassport: true,
    supportsMarketTransparency: true,
    supportsCPO: true,
    recommendedImagePreference: "factory_clean_first",
    recommendedPlacement: "inside_window",
    defaultPricingMode: "used_market_value_plus_addendum",
    tags: ["hyundai", "oem", "modern"],
    suggestedOEMs: ["Hyundai"],
  },
  {
    id: "used-window-oem-infiniti",
    name: "INFINITI Pre-Owned Window Sticker",
    category: "oem",
    family: "luxury_black",
    description: "INFINITI-themed luxury used window sticker with premium image, trust score, market story, and passport-first option.",
    component: UsedWindowLuxuryBlack,
    defaultBadge: "INFINITI Pre-Owned",
    ...core,
    supportsPassport: true,
    supportsMarketTransparency: true,
    supportsCPO: true,
    recommendedImagePreference: "transparent_first",
    recommendedPlacement: "inside_window",
    defaultPricingMode: "passport_live_price_only",
    tags: ["infiniti", "oem", "luxury"],
    suggestedOEMs: ["INFINITI"],
  },
  {
    id: "used-window-oem-kia",
    name: "Kia Pre-Owned Window Sticker",
    category: "oem",
    family: "modern_passport",
    description: "Kia-themed modern used sticker with OEM colors, factory-clean image, MPG, trust, and QR support.",
    component: UsedWindowModernPassport,
    defaultBadge: "Kia Pre-Owned",
    ...core,
    supportsPassport: true,
    supportsMarketTransparency: true,
    supportsCPO: true,
    recommendedImagePreference: "factory_clean_first",
    recommendedPlacement: "inside_window",
    defaultPricingMode: "used_market_value_plus_addendum",
    tags: ["kia", "oem", "modern"],
    suggestedOEMs: ["Kia"],
  },
  {
    id: "used-window-oem-lexus",
    name: "Lexus Pre-Owned Window Sticker",
    category: "oem",
    family: "luxury_black",
    description: "Lexus-themed luxury used sticker for L/Certified and pre-owned inventory.",
    component: UsedWindowLuxuryBlack,
    defaultBadge: "Lexus Pre-Owned",
    ...core,
    supportsPassport: true,
    supportsMarketTransparency: true,
    supportsCPO: true,
    recommendedImagePreference: "transparent_first",
    recommendedPlacement: "inside_window",
    defaultPricingMode: "passport_live_price_only",
    tags: ["lexus", "oem", "luxury"],
    suggestedOEMs: ["Lexus"],
  },
  {
    id: "used-window-oem-mazda",
    name: "Mazda Pre-Owned Window Sticker",
    category: "oem",
    family: "modern_passport",
    description: "Mazda-themed refined used sticker with modern design, clean image, MPG, and passport option.",
    component: UsedWindowModernPassport,
    defaultBadge: "Mazda Pre-Owned",
    ...core,
    supportsPassport: true,
    supportsMarketTransparency: true,
    supportsCPO: true,
    recommendedImagePreference: "factory_clean_first",
    recommendedPlacement: "inside_window",
    defaultPricingMode: "used_market_value_plus_addendum",
    tags: ["mazda", "oem", "modern"],
    suggestedOEMs: ["Mazda"],
  },
  {
    id: "used-window-oem-mercedes-benz",
    name: "Mercedes-Benz Pre-Owned Window Sticker",
    category: "oem",
    family: "luxury_black",
    description: "Mercedes-Benz-themed executive used window sticker with premium layout and passport-first strategy.",
    component: UsedWindowLuxuryBlack,
    defaultBadge: "Mercedes-Benz Pre-Owned",
    ...core,
    supportsPassport: true,
    supportsMarketTransparency: true,
    supportsCPO: true,
    recommendedImagePreference: "transparent_first",
    recommendedPlacement: "inside_window",
    defaultPricingMode: "passport_live_price_only",
    tags: ["mercedes-benz", "oem", "luxury"],
    suggestedOEMs: ["Mercedes-Benz"],
  },
  {
    id: "used-window-oem-nissan",
    name: "Nissan Pre-Owned Window Sticker",
    category: "oem",
    family: "modern_passport",
    description: "Nissan-themed used window sticker with factory-clean image and flexible passport/market modules.",
    component: UsedWindowModernPassport,
    defaultBadge: "Nissan Pre-Owned",
    ...core,
    supportsPassport: true,
    supportsMarketTransparency: true,
    supportsCPO: true,
    recommendedImagePreference: "factory_clean_first",
    recommendedPlacement: "inside_window",
    defaultPricingMode: "used_market_value_plus_addendum",
    tags: ["nissan", "oem", "cpo"],
    suggestedOEMs: ["Nissan"],
  },
  {
    id: "used-window-oem-subaru",
    name: "Subaru Pre-Owned Window Sticker",
    category: "oem",
    family: "traditional_oem",
    description: "Subaru-themed trust-oriented used sticker with OEM feel, MPG, image, and passport option.",
    component: UsedWindowTraditionalOEM,
    defaultBadge: "Subaru Pre-Owned",
    ...core,
    supportsPassport: true,
    supportsMarketTransparency: true,
    supportsCPO: true,
    recommendedImagePreference: "factory_clean_first",
    recommendedPlacement: "outside_window",
    defaultPricingMode: "used_market_value_plus_addendum",
    tags: ["subaru", "oem", "trust"],
    suggestedOEMs: ["Subaru"],
  },
  {
    id: "used-window-oem-toyota",
    name: "Toyota Pre-Owned Window Sticker",
    category: "oem",
    family: "traditional_oem",
    description: "Toyota-themed OEM-style used sticker with clean image, MPG, trust source, and optional passport.",
    component: UsedWindowTraditionalOEM,
    defaultBadge: "Toyota Pre-Owned",
    ...core,
    supportsPassport: true,
    supportsMarketTransparency: true,
    supportsCPO: true,
    recommendedImagePreference: "factory_clean_first",
    recommendedPlacement: "inside_window",
    defaultPricingMode: "used_market_value_plus_addendum",
    tags: ["toyota", "oem", "certified"],
    suggestedOEMs: ["Toyota"],
  },
  {
    id: "used-window-oem-volkswagen",
    name: "Volkswagen Pre-Owned Window Sticker",
    category: "oem",
    family: "modern_passport",
    description: "Volkswagen-themed clean modern used sticker with factory image, MPG, and digital modules.",
    component: UsedWindowModernPassport,
    defaultBadge: "Volkswagen Pre-Owned",
    ...core,
    supportsPassport: true,
    supportsMarketTransparency: true,
    supportsCPO: true,
    recommendedImagePreference: "factory_clean_first",
    recommendedPlacement: "inside_window",
    defaultPricingMode: "used_market_value_plus_addendum",
    tags: ["volkswagen", "vw", "oem"],
    suggestedOEMs: ["Volkswagen"],
  },
  {
    id: "used-window-oem-volvo",
    name: "Volvo Pre-Owned Window Sticker",
    category: "oem",
    family: "luxury_black",
    description: "Volvo-themed premium trust sticker with clean image, safety/value story, and passport support.",
    component: UsedWindowLuxuryBlack,
    defaultBadge: "Volvo Pre-Owned",
    ...core,
    supportsPassport: true,
    supportsMarketTransparency: true,
    supportsCPO: true,
    recommendedImagePreference: "transparent_first",
    recommendedPlacement: "inside_window",
    defaultPricingMode: "passport_live_price_only",
    tags: ["volvo", "oem", "premium"],
    suggestedOEMs: ["Volvo"],
  },
];

export const USED_WINDOW_STICKER_CATALOG_BY_ID = Object.fromEntries(
  USED_WINDOW_STICKER_CATALOG_50.map((template) => [template.id, template]),
);

export const USED_WINDOW_STICKER_CATEGORIES: UsedWindowStickerCategory[] = [
  "core",
  "pricing",
  "certification",
  "dealer_value",
  "market_transparency",
  "luxury",
  "specialty",
  "oem",
];
