// 50-template used vehicle addendum catalog.
// These are dealer-selectable 4.5x11 addendum definitions that reuse core layout families
// while allowing OEM/dealer colors, pricing modes, market transparency, certification, and placement rules.

import {
  UsedAddendumCPOFocus,
  UsedAddendumDealerDifference,
  UsedAddendumLuxuryBlack,
  UsedAddendumMarketTransparency,
  UsedAddendumMinimalCompliance,
  UsedAddendumModernBlue,
  UsedAddendumOnePrice,
  UsedAddendumTraditionalOEM,
} from "./UsedAddendumPack";

export type UsedAddendumCategory =
  | "core"
  | "pricing"
  | "certification"
  | "dealer_value"
  | "market_transparency"
  | "luxury"
  | "specialty"
  | "oem";

export type UsedAddendumLayoutFamily =
  | "modern_blue"
  | "traditional_oem"
  | "luxury_black"
  | "cpo_focus"
  | "one_price"
  | "dealer_difference"
  | "minimal_compliance"
  | "market_transparency";

export type UsedAddendumTemplateDefinition = {
  id: string;
  name: string;
  category: UsedAddendumCategory;
  family: UsedAddendumLayoutFamily;
  description: string;
  component: typeof UsedAddendumModernBlue;
  defaultBadge: string;
  supportsDealerTheme: true;
  supportsOEMTheme: true;
  supportsMarketTransparency: boolean;
  supportsCPO: boolean;
  recommendedPlacement: "inside_window" | "outside_window" | "either";
  defaultPricingMode:
    | "used_addendum_only"
    | "used_market_value_plus_addendum"
    | "used_live_price_plus_addendum"
    | "passport_live_price_only";
  tags: string[];
  suggestedOEMs?: string[];
};

const core = {
  supportsDealerTheme: true,
  supportsOEMTheme: true,
} as const;

export const USED_ADDENDUM_CATALOG_50: UsedAddendumTemplateDefinition[] = [
  {
    id: "used-core-modern-blue",
    name: "Modern Blue Used Addendum",
    category: "core",
    family: "modern_blue",
    description: "Clean SaaS-style used vehicle addendum for general inventory.",
    component: UsedAddendumModernBlue,
    defaultBadge: "Used Vehicle Addendum",
    ...core,
    supportsMarketTransparency: true,
    supportsCPO: false,
    recommendedPlacement: "either",
    defaultPricingMode: "used_market_value_plus_addendum",
    tags: ["general", "modern", "blue", "passport"],
  },
  {
    id: "used-core-modern-dark",
    name: "Modern Dark Used Addendum",
    category: "core",
    family: "luxury_black",
    description: "High-contrast modern addendum with darker framing for stronger curb appeal.",
    component: UsedAddendumLuxuryBlack,
    defaultBadge: "Used Vehicle Addendum",
    ...core,
    supportsMarketTransparency: true,
    supportsCPO: false,
    recommendedPlacement: "outside_window",
    defaultPricingMode: "used_market_value_plus_addendum",
    tags: ["modern", "dark", "high-contrast"],
  },
  {
    id: "used-core-traditional-oem",
    name: "Traditional OEM Used Addendum",
    category: "core",
    family: "traditional_oem",
    description: "Conservative OEM-style addendum for franchise stores.",
    component: UsedAddendumTraditionalOEM,
    defaultBadge: "OEM-Style Addendum",
    ...core,
    supportsMarketTransparency: true,
    supportsCPO: true,
    recommendedPlacement: "inside_window",
    defaultPricingMode: "used_market_value_plus_addendum",
    tags: ["traditional", "franchise", "oem"],
  },
  {
    id: "used-core-traditional-compact",
    name: "Traditional Compact Addendum",
    category: "core",
    family: "traditional_oem",
    description: "Compact dealer addendum focused on installed items and clean totals.",
    component: UsedAddendumTraditionalOEM,
    defaultBadge: "Vehicle Addendum",
    ...core,
    supportsMarketTransparency: false,
    supportsCPO: false,
    recommendedPlacement: "inside_window",
    defaultPricingMode: "used_addendum_only",
    tags: ["traditional", "compact", "installed-items"],
  },
  {
    id: "used-core-minimal-compliance",
    name: "Minimal Compliance Addendum",
    category: "core",
    family: "minimal_compliance",
    description: "Simple addendum for stores that want clean, direct item disclosure.",
    component: UsedAddendumMinimalCompliance,
    defaultBadge: "Vehicle Addendum",
    ...core,
    supportsMarketTransparency: false,
    supportsCPO: false,
    recommendedPlacement: "either",
    defaultPricingMode: "used_addendum_only",
    tags: ["minimal", "compliance", "simple"],
  },
  {
    id: "used-core-minimal-premium",
    name: "Minimal Premium Addendum",
    category: "core",
    family: "minimal_compliance",
    description: "Refined minimal addendum for premium dealers that want less clutter.",
    component: UsedAddendumMinimalCompliance,
    defaultBadge: "Premium Addendum",
    ...core,
    supportsMarketTransparency: true,
    supportsCPO: false,
    recommendedPlacement: "inside_window",
    defaultPricingMode: "passport_live_price_only",
    tags: ["minimal", "premium", "passport-first"],
  },
  {
    id: "used-core-contemporary-dealer",
    name: "Contemporary Dealer Addendum",
    category: "core",
    family: "modern_blue",
    description: "Contemporary dealer-branded addendum for mainstream used car operations.",
    component: UsedAddendumModernBlue,
    defaultBadge: "Dealer Addendum",
    ...core,
    supportsMarketTransparency: true,
    supportsCPO: false,
    recommendedPlacement: "either",
    defaultPricingMode: "used_live_price_plus_addendum",
    tags: ["contemporary", "dealer-brand", "mainstream"],
  },
  {
    id: "used-core-contemporary-plus",
    name: "Contemporary Plus Addendum",
    category: "core",
    family: "modern_blue",
    description: "Dealer-branded version with extra room for ownership benefits and passport callouts.",
    component: UsedAddendumModernBlue,
    defaultBadge: "Dealer Value Addendum",
    ...core,
    supportsMarketTransparency: true,
    supportsCPO: true,
    recommendedPlacement: "outside_window",
    defaultPricingMode: "used_market_value_plus_addendum",
    tags: ["contemporary", "benefits", "qr"],
  },
  {
    id: "used-core-inventory-basic",
    name: "Inventory Basic Addendum",
    category: "core",
    family: "minimal_compliance",
    description: "Fast-print internal/external addendum for high-volume used inventory.",
    component: UsedAddendumMinimalCompliance,
    defaultBadge: "Inventory Addendum",
    ...core,
    supportsMarketTransparency: false,
    supportsCPO: false,
    recommendedPlacement: "either",
    defaultPricingMode: "used_addendum_only",
    tags: ["high-volume", "basic", "fast-print"],
  },
  {
    id: "used-core-passport-first",
    name: "Passport First Addendum",
    category: "core",
    family: "modern_blue",
    description: "Designed to drive QR scans by keeping live price inside the passport.",
    component: UsedAddendumModernBlue,
    defaultBadge: "Scan For Live Price",
    ...core,
    supportsMarketTransparency: true,
    supportsCPO: true,
    recommendedPlacement: "outside_window",
    defaultPricingMode: "passport_live_price_only",
    tags: ["passport", "qr", "live-price"],
  },

  {
    id: "used-pricing-one-price",
    name: "One Price Store Addendum",
    category: "pricing",
    family: "one_price",
    description: "Clear no-haggle pricing presentation for one-price stores.",
    component: UsedAddendumOnePrice,
    defaultBadge: "One Price Store",
    ...core,
    supportsMarketTransparency: true,
    supportsCPO: false,
    recommendedPlacement: "outside_window",
    defaultPricingMode: "used_live_price_plus_addendum",
    tags: ["one-price", "no-haggle", "transparent"],
  },
  {
    id: "used-pricing-best-price",
    name: "Best Price Addendum",
    category: "pricing",
    family: "one_price",
    description: "Built for dealers using Best Price or Best Price First terminology.",
    component: UsedAddendumOnePrice,
    defaultBadge: "Best Price Addendum",
    ...core,
    supportsMarketTransparency: true,
    supportsCPO: false,
    recommendedPlacement: "either",
    defaultPricingMode: "used_live_price_plus_addendum",
    tags: ["best-price", "pricing", "transparent"],
  },
  {
    id: "used-pricing-market-price",
    name: "Market Price Addendum",
    category: "pricing",
    family: "market_transparency",
    description: "Uses market value on print and live selling price in the passport.",
    component: UsedAddendumMarketTransparency,
    defaultBadge: "Market Price Addendum",
    ...core,
    supportsMarketTransparency: true,
    supportsCPO: false,
    recommendedPlacement: "either",
    defaultPricingMode: "used_market_value_plus_addendum",
    tags: ["market-price", "market-value", "passport"],
  },
  {
    id: "used-pricing-no-haggle",
    name: "No-Haggle Addendum",
    category: "pricing",
    family: "one_price",
    description: "Straightforward pricing addendum for no-haggle sales operations.",
    component: UsedAddendumOnePrice,
    defaultBadge: "No-Haggle Price",
    ...core,
    supportsMarketTransparency: true,
    supportsCPO: false,
    recommendedPlacement: "outside_window",
    defaultPricingMode: "used_live_price_plus_addendum",
    tags: ["no-haggle", "simple", "price"],
  },
  {
    id: "used-pricing-internet-price",
    name: "Internet Price Addendum",
    category: "pricing",
    family: "modern_blue",
    description: "For dealers who want the printed addendum to reference online pricing strategy.",
    component: UsedAddendumModernBlue,
    defaultBadge: "Internet Price Addendum",
    ...core,
    supportsMarketTransparency: true,
    supportsCPO: false,
    recommendedPlacement: "inside_window",
    defaultPricingMode: "passport_live_price_only",
    tags: ["internet-price", "online", "qr"],
  },
  {
    id: "used-pricing-value-leader",
    name: "Value Leader Addendum",
    category: "pricing",
    family: "dealer_difference",
    description: "Highlights the vehicle as a strong value against market data.",
    component: UsedAddendumDealerDifference,
    defaultBadge: "Value Leader",
    ...core,
    supportsMarketTransparency: true,
    supportsCPO: false,
    recommendedPlacement: "outside_window",
    defaultPricingMode: "used_market_value_plus_addendum",
    tags: ["value", "market", "dealer-difference"],
  },
  {
    id: "used-pricing-savings-comparison",
    name: "Savings Comparison Addendum",
    category: "pricing",
    family: "market_transparency",
    description: "Built around market comparison and savings storytelling.",
    component: UsedAddendumMarketTransparency,
    defaultBadge: "Savings Verified",
    ...core,
    supportsMarketTransparency: true,
    supportsCPO: false,
    recommendedPlacement: "outside_window",
    defaultPricingMode: "used_market_value_plus_addendum",
    tags: ["savings", "comparison", "market"],
  },
  {
    id: "used-pricing-passport-live-price",
    name: "Passport Live Price Addendum",
    category: "pricing",
    family: "modern_blue",
    description: "Keeps the printed sticker stable while the passport shows today's price.",
    component: UsedAddendumModernBlue,
    defaultBadge: "Scan For Today's Price",
    ...core,
    supportsMarketTransparency: true,
    supportsCPO: true,
    recommendedPlacement: "outside_window",
    defaultPricingMode: "passport_live_price_only",
    tags: ["live-price", "passport", "scan"],
  },

  {
    id: "used-cert-oem-cpo",
    name: "OEM CPO Addendum",
    category: "certification",
    family: "cpo_focus",
    description: "Certification-first addendum for OEM certified used vehicles.",
    component: UsedAddendumCPOFocus,
    defaultBadge: "OEM Certified",
    ...core,
    supportsMarketTransparency: true,
    supportsCPO: true,
    recommendedPlacement: "inside_window",
    defaultPricingMode: "used_market_value_plus_addendum",
    tags: ["oem-cpo", "certified", "warranty"],
  },
  {
    id: "used-cert-dealer-cpo",
    name: "Dealer Certified Addendum",
    category: "certification",
    family: "cpo_focus",
    description: "Flexible dealer-certified addendum for non-OEM certification programs.",
    component: UsedAddendumCPOFocus,
    defaultBadge: "Dealer Certified",
    ...core,
    supportsMarketTransparency: true,
    supportsCPO: true,
    recommendedPlacement: "either",
    defaultPricingMode: "used_market_value_plus_addendum",
    tags: ["dealer-certified", "coverage", "warranty"],
  },
  {
    id: "used-cert-certified-plus",
    name: "Certified Plus Addendum",
    category: "certification",
    family: "cpo_focus",
    description: "Upgraded certification addendum for enhanced dealer coverage programs.",
    component: UsedAddendumCPOFocus,
    defaultBadge: "Certified Plus",
    ...core,
    supportsMarketTransparency: true,
    supportsCPO: true,
    recommendedPlacement: "outside_window",
    defaultPricingMode: "used_market_value_plus_addendum",
    tags: ["certified-plus", "upgrade", "coverage"],
  },
  {
    id: "used-cert-certified-elite",
    name: "Certified Elite Addendum",
    category: "certification",
    family: "luxury_black",
    description: "Premium certification presentation for high-line CPO operations.",
    component: UsedAddendumLuxuryBlack,
    defaultBadge: "Certified Elite",
    ...core,
    supportsMarketTransparency: true,
    supportsCPO: true,
    recommendedPlacement: "inside_window",
    defaultPricingMode: "used_market_value_plus_addendum",
    tags: ["elite", "luxury", "certified"],
  },
  {
    id: "used-cert-warranty-focus",
    name: "Warranty Focus Addendum",
    category: "certification",
    family: "cpo_focus",
    description: "Highlights powertrain, bumper-to-bumper, or limited warranty coverage.",
    component: UsedAddendumCPOFocus,
    defaultBadge: "Warranty Included",
    ...core,
    supportsMarketTransparency: false,
    supportsCPO: true,
    recommendedPlacement: "either",
    defaultPricingMode: "used_addendum_only",
    tags: ["warranty", "coverage", "confidence"],
  },
  {
    id: "used-cert-protection-focus",
    name: "Protection Focus Addendum",
    category: "certification",
    family: "dealer_difference",
    description: "Designed around dealer protection products and coverage options.",
    component: UsedAddendumDealerDifference,
    defaultBadge: "Protection Included",
    ...core,
    supportsMarketTransparency: false,
    supportsCPO: true,
    recommendedPlacement: "inside_window",
    defaultPricingMode: "used_addendum_only",
    tags: ["protection", "coverage", "dealer-value"],
  },
  {
    id: "used-cert-finance-upgrade",
    name: "Finance Upgrade Certification Addendum",
    category: "certification",
    family: "cpo_focus",
    description: "Supports stair-step certification upgrades tied to dealer-arranged financing.",
    component: UsedAddendumCPOFocus,
    defaultBadge: "Finance Upgrade Eligible",
    ...core,
    supportsMarketTransparency: true,
    supportsCPO: true,
    recommendedPlacement: "inside_window",
    defaultPricingMode: "passport_live_price_only",
    tags: ["finance", "upgrade", "stair-step", "cpo"],
  },
  {
    id: "used-cert-multi-tier",
    name: "Multi-Tier Certification Addendum",
    category: "certification",
    family: "cpo_focus",
    description: "For dealers with base, silver, gold, and platinum certification levels.",
    component: UsedAddendumCPOFocus,
    defaultBadge: "Certification Options",
    ...core,
    supportsMarketTransparency: true,
    supportsCPO: true,
    recommendedPlacement: "inside_window",
    defaultPricingMode: "passport_live_price_only",
    tags: ["tiered", "certification", "options"],
  },

  {
    id: "used-value-dealer-difference",
    name: "Dealer Difference Addendum",
    category: "dealer_value",
    family: "dealer_difference",
    description: "Benefit-heavy addendum showing why to buy from this dealer.",
    component: UsedAddendumDealerDifference,
    defaultBadge: "Dealer Difference",
    ...core,
    supportsMarketTransparency: true,
    supportsCPO: false,
    recommendedPlacement: "outside_window",
    defaultPricingMode: "used_market_value_plus_addendum",
    tags: ["dealer-difference", "benefits", "trust"],
  },
  {
    id: "used-value-why-buy-here",
    name: "Why Buy Here Addendum",
    category: "dealer_value",
    family: "dealer_difference",
    description: "A dealer value proposition addendum for meticulously run used-car operations.",
    component: UsedAddendumDealerDifference,
    defaultBadge: "Why Buy Here",
    ...core,
    supportsMarketTransparency: true,
    supportsCPO: false,
    recommendedPlacement: "outside_window",
    defaultPricingMode: "passport_live_price_only",
    tags: ["why-buy", "trust", "dealer-value"],
  },
  {
    id: "used-value-benefits-package",
    name: "Benefits Package Addendum",
    category: "dealer_value",
    family: "dealer_difference",
    description: "Focuses on bundled benefits, included protections, and ownership value.",
    component: UsedAddendumDealerDifference,
    defaultBadge: "Benefits Package",
    ...core,
    supportsMarketTransparency: false,
    supportsCPO: true,
    recommendedPlacement: "inside_window",
    defaultPricingMode: "used_addendum_only",
    tags: ["benefits", "ownership", "bundle"],
  },
  {
    id: "used-value-vip-ownership",
    name: "VIP Ownership Addendum",
    category: "dealer_value",
    family: "luxury_black",
    description: "Premium benefits addendum for VIP or concierge ownership packages.",
    component: UsedAddendumLuxuryBlack,
    defaultBadge: "VIP Ownership",
    ...core,
    supportsMarketTransparency: true,
    supportsCPO: true,
    recommendedPlacement: "inside_window",
    defaultPricingMode: "passport_live_price_only",
    tags: ["vip", "ownership", "luxury"],
  },
  {
    id: "used-value-lifetime-warranty",
    name: "Lifetime Warranty Addendum",
    category: "dealer_value",
    family: "cpo_focus",
    description: "Warranty-forward addendum for dealers offering lifetime powertrain coverage.",
    component: UsedAddendumCPOFocus,
    defaultBadge: "Lifetime Warranty",
    ...core,
    supportsMarketTransparency: false,
    supportsCPO: true,
    recommendedPlacement: "outside_window",
    defaultPricingMode: "used_addendum_only",
    tags: ["lifetime-warranty", "powertrain", "coverage"],
  },
  {
    id: "used-value-service-included",
    name: "Service Included Addendum",
    category: "dealer_value",
    family: "dealer_difference",
    description: "Highlights included oil changes, inspections, service records, or maintenance perks.",
    component: UsedAddendumDealerDifference,
    defaultBadge: "Service Included",
    ...core,
    supportsMarketTransparency: false,
    supportsCPO: false,
    recommendedPlacement: "inside_window",
    defaultPricingMode: "used_addendum_only",
    tags: ["service", "maintenance", "included"],
  },
  {
    id: "used-value-roadside-included",
    name: "Roadside Included Addendum",
    category: "dealer_value",
    family: "dealer_difference",
    description: "Designed for dealers emphasizing roadside assistance and ownership support.",
    component: UsedAddendumDealerDifference,
    defaultBadge: "Roadside Included",
    ...core,
    supportsMarketTransparency: false,
    supportsCPO: false,
    recommendedPlacement: "inside_window",
    defaultPricingMode: "used_addendum_only",
    tags: ["roadside", "support", "benefits"],
  },
  {
    id: "used-value-maintenance-included",
    name: "Maintenance Included Addendum",
    category: "dealer_value",
    family: "dealer_difference",
    description: "For dealers offering prepaid or included maintenance with purchase.",
    component: UsedAddendumDealerDifference,
    defaultBadge: "Maintenance Included",
    ...core,
    supportsMarketTransparency: false,
    supportsCPO: false,
    recommendedPlacement: "inside_window",
    defaultPricingMode: "used_addendum_only",
    tags: ["maintenance", "service", "ownership"],
  },

  {
    id: "used-market-transparency",
    name: "Market Transparency Addendum",
    category: "market_transparency",
    family: "market_transparency",
    description: "Displays market value and encourages customers to scan for live selling price.",
    component: UsedAddendumMarketTransparency,
    defaultBadge: "Market Transparency",
    ...core,
    supportsMarketTransparency: true,
    supportsCPO: false,
    recommendedPlacement: "outside_window",
    defaultPricingMode: "used_market_value_plus_addendum",
    tags: ["market", "transparency", "scan"],
  },
  {
    id: "used-market-intelligence",
    name: "Market Intelligence Addendum",
    category: "market_transparency",
    family: "market_transparency",
    description: "More analytical addendum for sophisticated stores using MarketCheck and Black Book.",
    component: UsedAddendumMarketTransparency,
    defaultBadge: "Market Intelligence",
    ...core,
    supportsMarketTransparency: true,
    supportsCPO: true,
    recommendedPlacement: "inside_window",
    defaultPricingMode: "used_market_value_plus_addendum",
    tags: ["marketcheck", "black-book", "analytics"],
  },
  {
    id: "used-market-vehicle-passport",
    name: "Vehicle Passport Addendum",
    category: "market_transparency",
    family: "modern_blue",
    description: "QR-forward addendum where the passport carries live price, docs, and market proof.",
    component: UsedAddendumModernBlue,
    defaultBadge: "Vehicle Passport",
    ...core,
    supportsMarketTransparency: true,
    supportsCPO: true,
    recommendedPlacement: "outside_window",
    defaultPricingMode: "passport_live_price_only",
    tags: ["passport", "qr", "truth"],
  },
  {
    id: "used-market-fair-price-verified",
    name: "Fair Price Verified Addendum",
    category: "market_transparency",
    family: "market_transparency",
    description: "Positions the vehicle around fair market value and transparent data.",
    component: UsedAddendumMarketTransparency,
    defaultBadge: "Fair Price Verified",
    ...core,
    supportsMarketTransparency: true,
    supportsCPO: false,
    recommendedPlacement: "outside_window",
    defaultPricingMode: "used_market_value_plus_addendum",
    tags: ["fair-price", "verified", "market"],
  },
  {
    id: "used-market-competitive-analysis",
    name: "Competitive Market Analysis Addendum",
    category: "market_transparency",
    family: "market_transparency",
    description: "For dealers who want to show comps, market averages, and value proof.",
    component: UsedAddendumMarketTransparency,
    defaultBadge: "Competitive Analysis",
    ...core,
    supportsMarketTransparency: true,
    supportsCPO: false,
    recommendedPlacement: "inside_window",
    defaultPricingMode: "used_market_value_plus_addendum",
    tags: ["competitive", "comps", "analysis"],
  },
  {
    id: "used-market-price-confidence",
    name: "Price Confidence Addendum",
    category: "market_transparency",
    family: "market_transparency",
    description: "Simple market-backed addendum focused on confidence and trust.",
    component: UsedAddendumMarketTransparency,
    defaultBadge: "Price Confidence",
    ...core,
    supportsMarketTransparency: true,
    supportsCPO: false,
    recommendedPlacement: "outside_window",
    defaultPricingMode: "used_market_value_plus_addendum",
    tags: ["confidence", "trust", "market"],
  },

  {
    id: "used-luxury-executive-black",
    name: "Executive Black Addendum",
    category: "luxury",
    family: "luxury_black",
    description: "Dark luxury presentation for premium pre-owned vehicles.",
    component: UsedAddendumLuxuryBlack,
    defaultBadge: "Executive Collection",
    ...core,
    supportsMarketTransparency: true,
    supportsCPO: true,
    recommendedPlacement: "inside_window",
    defaultPricingMode: "passport_live_price_only",
    tags: ["luxury", "executive", "black"],
    suggestedOEMs: ["INFINITI", "Lexus", "BMW", "Mercedes-Benz", "Audi", "Cadillac", "Genesis"],
  },
  {
    id: "used-luxury-executive-white",
    name: "Executive White Addendum",
    category: "luxury",
    family: "minimal_compliance",
    description: "Bright luxury addendum with restrained premium styling.",
    component: UsedAddendumMinimalCompliance,
    defaultBadge: "Executive Addendum",
    ...core,
    supportsMarketTransparency: true,
    supportsCPO: true,
    recommendedPlacement: "inside_window",
    defaultPricingMode: "passport_live_price_only",
    tags: ["luxury", "white", "minimal"],
    suggestedOEMs: ["Lexus", "Acura", "Volvo", "Lincoln", "Genesis"],
  },
  {
    id: "used-luxury-concierge",
    name: "Luxury Concierge Addendum",
    category: "luxury",
    family: "luxury_black",
    description: "Concierge-style addendum for premium ownership experiences.",
    component: UsedAddendumLuxuryBlack,
    defaultBadge: "Concierge Ownership",
    ...core,
    supportsMarketTransparency: true,
    supportsCPO: true,
    recommendedPlacement: "inside_window",
    defaultPricingMode: "passport_live_price_only",
    tags: ["concierge", "premium", "ownership"],
    suggestedOEMs: ["Mercedes-Benz", "BMW", "Audi", "Porsche", "Cadillac"],
  },
  {
    id: "used-luxury-premium-ownership",
    name: "Premium Ownership Addendum",
    category: "luxury",
    family: "luxury_black",
    description: "Balances premium value props, passport trust, and installed products.",
    component: UsedAddendumLuxuryBlack,
    defaultBadge: "Premium Ownership",
    ...core,
    supportsMarketTransparency: true,
    supportsCPO: true,
    recommendedPlacement: "outside_window",
    defaultPricingMode: "used_market_value_plus_addendum",
    tags: ["premium", "ownership", "benefits"],
  },
  {
    id: "used-luxury-signature-collection",
    name: "Signature Collection Addendum",
    category: "luxury",
    family: "luxury_black",
    description: "Top-tier visual style for curated high-line pre-owned inventory.",
    component: UsedAddendumLuxuryBlack,
    defaultBadge: "Signature Collection",
    ...core,
    supportsMarketTransparency: true,
    supportsCPO: true,
    recommendedPlacement: "outside_window",
    defaultPricingMode: "passport_live_price_only",
    tags: ["signature", "collection", "high-line"],
    suggestedOEMs: ["INFINITI", "Lexus", "BMW", "Mercedes-Benz", "Audi", "Cadillac", "Genesis", "Porsche"],
  },

  {
    id: "used-specialty-service-loaner",
    name: "Service Loaner Addendum",
    category: "specialty",
    family: "traditional_oem",
    description: "For retired service loaners that need OEM-style clarity and disclosure.",
    component: UsedAddendumTraditionalOEM,
    defaultBadge: "Service Loaner",
    ...core,
    supportsMarketTransparency: true,
    supportsCPO: true,
    recommendedPlacement: "inside_window",
    defaultPricingMode: "used_market_value_plus_addendum",
    tags: ["loaner", "service", "demo"],
  },
  {
    id: "used-specialty-demo-vehicle",
    name: "Demo Vehicle Addendum",
    category: "specialty",
    family: "traditional_oem",
    description: "For demo and executive vehicles with installed accessories and mileage notes.",
    component: UsedAddendumTraditionalOEM,
    defaultBadge: "Demo Vehicle",
    ...core,
    supportsMarketTransparency: true,
    supportsCPO: true,
    recommendedPlacement: "inside_window",
    defaultPricingMode: "used_market_value_plus_addendum",
    tags: ["demo", "executive", "mileage"],
  },
  {
    id: "used-specialty-manager-special",
    name: "Manager Special Addendum",
    category: "specialty",
    family: "dealer_difference",
    description: "Promotional addendum for manager specials and spotlight vehicles.",
    component: UsedAddendumDealerDifference,
    defaultBadge: "Manager Special",
    ...core,
    supportsMarketTransparency: true,
    supportsCPO: false,
    recommendedPlacement: "outside_window",
    defaultPricingMode: "passport_live_price_only",
    tags: ["manager-special", "promo", "spotlight"],
  },
  {
    id: "used-specialty-ev-hybrid",
    name: "EV / Hybrid Focus Addendum",
    category: "specialty",
    family: "modern_blue",
    description: "Addendum for EV/hybrid used vehicles with range, charging, and efficiency benefits.",
    component: UsedAddendumModernBlue,
    defaultBadge: "EV / Hybrid Addendum",
    ...core,
    supportsMarketTransparency: true,
    supportsCPO: false,
    recommendedPlacement: "inside_window",
    defaultPricingMode: "used_market_value_plus_addendum",
    tags: ["ev", "hybrid", "efficiency"],
  },
  {
    id: "used-specialty-commercial-fleet",
    name: "Commercial / Fleet Addendum",
    category: "specialty",
    family: "minimal_compliance",
    description: "Simple, durable addendum for commercial vehicles, vans, and fleet units.",
    component: UsedAddendumMinimalCompliance,
    defaultBadge: "Commercial Vehicle",
    ...core,
    supportsMarketTransparency: false,
    supportsCPO: false,
    recommendedPlacement: "outside_window",
    defaultPricingMode: "used_addendum_only",
    tags: ["commercial", "fleet", "van", "work-truck"],
  },

  {
    id: "used-oem-acura",
    name: "Acura Used Addendum",
    category: "oem",
    family: "luxury_black",
    description: "OEM-themed addendum for Acura pre-owned stores.",
    component: UsedAddendumLuxuryBlack,
    defaultBadge: "Acura Pre-Owned",
    ...core,
    supportsMarketTransparency: true,
    supportsCPO: true,
    recommendedPlacement: "inside_window",
    defaultPricingMode: "used_market_value_plus_addendum",
    tags: ["acura", "oem", "luxury"],
    suggestedOEMs: ["Acura"],
  },
  {
    id: "used-oem-audi",
    name: "Audi Used Addendum",
    category: "oem",
    family: "luxury_black",
    description: "Premium dark addendum for Audi pre-owned inventory.",
    component: UsedAddendumLuxuryBlack,
    defaultBadge: "Audi Pre-Owned",
    ...core,
    supportsMarketTransparency: true,
    supportsCPO: true,
    recommendedPlacement: "inside_window",
    defaultPricingMode: "passport_live_price_only",
    tags: ["audi", "oem", "luxury"],
    suggestedOEMs: ["Audi"],
  },
  {
    id: "used-oem-bmw",
    name: "BMW Used Addendum",
    category: "oem",
    family: "luxury_black",
    description: "Premium addendum for BMW used and certified inventory.",
    component: UsedAddendumLuxuryBlack,
    defaultBadge: "BMW Pre-Owned",
    ...core,
    supportsMarketTransparency: true,
    supportsCPO: true,
    recommendedPlacement: "inside_window",
    defaultPricingMode: "passport_live_price_only",
    tags: ["bmw", "oem", "luxury"],
    suggestedOEMs: ["BMW"],
  },
  {
    id: "used-oem-cadillac",
    name: "Cadillac Used Addendum",
    category: "oem",
    family: "luxury_black",
    description: "Luxury addendum for Cadillac pre-owned vehicles.",
    component: UsedAddendumLuxuryBlack,
    defaultBadge: "Cadillac Pre-Owned",
    ...core,
    supportsMarketTransparency: true,
    supportsCPO: true,
    recommendedPlacement: "inside_window",
    defaultPricingMode: "used_market_value_plus_addendum",
    tags: ["cadillac", "oem", "luxury"],
    suggestedOEMs: ["Cadillac"],
  },
  {
    id: "used-oem-chevrolet",
    name: "Chevrolet Used Addendum",
    category: "oem",
    family: "traditional_oem",
    description: "Franchise-friendly addendum for Chevrolet used operations.",
    component: UsedAddendumTraditionalOEM,
    defaultBadge: "Chevrolet Pre-Owned",
    ...core,
    supportsMarketTransparency: true,
    supportsCPO: true,
    recommendedPlacement: "outside_window",
    defaultPricingMode: "used_market_value_plus_addendum",
    tags: ["chevrolet", "oem", "franchise"],
    suggestedOEMs: ["Chevrolet"],
  },
  {
    id: "used-oem-ford",
    name: "Ford Used Addendum",
    category: "oem",
    family: "traditional_oem",
    description: "OEM-style addendum for Ford Blue Advantage and used inventory.",
    component: UsedAddendumTraditionalOEM,
    defaultBadge: "Ford Pre-Owned",
    ...core,
    supportsMarketTransparency: true,
    supportsCPO: true,
    recommendedPlacement: "outside_window",
    defaultPricingMode: "used_market_value_plus_addendum",
    tags: ["ford", "oem", "blue-advantage"],
    suggestedOEMs: ["Ford"],
  },
  {
    id: "used-oem-honda",
    name: "Honda Used Addendum",
    category: "oem",
    family: "traditional_oem",
    description: "Clean OEM-style addendum for Honda and HondaTrue programs.",
    component: UsedAddendumTraditionalOEM,
    defaultBadge: "Honda Pre-Owned",
    ...core,
    supportsMarketTransparency: true,
    supportsCPO: true,
    recommendedPlacement: "inside_window",
    defaultPricingMode: "used_market_value_plus_addendum",
    tags: ["honda", "oem", "hondatrue"],
    suggestedOEMs: ["Honda"],
  },
  {
    id: "used-oem-hyundai",
    name: "Hyundai Used Addendum",
    category: "oem",
    family: "modern_blue",
    description: "Modern addendum for Hyundai used and certified stores.",
    component: UsedAddendumModernBlue,
    defaultBadge: "Hyundai Pre-Owned",
    ...core,
    supportsMarketTransparency: true,
    supportsCPO: true,
    recommendedPlacement: "inside_window",
    defaultPricingMode: "used_market_value_plus_addendum",
    tags: ["hyundai", "oem", "cpo"],
    suggestedOEMs: ["Hyundai"],
  },
  {
    id: "used-oem-infiniti",
    name: "INFINITI Used Addendum",
    category: "oem",
    family: "luxury_black",
    description: "Premium addendum for INFINITI used and certified inventory.",
    component: UsedAddendumLuxuryBlack,
    defaultBadge: "INFINITI Pre-Owned",
    ...core,
    supportsMarketTransparency: true,
    supportsCPO: true,
    recommendedPlacement: "inside_window",
    defaultPricingMode: "passport_live_price_only",
    tags: ["infiniti", "oem", "luxury"],
    suggestedOEMs: ["INFINITI"],
  },
  {
    id: "used-oem-jeep-ram-dodge-chrysler",
    name: "Jeep / RAM / Dodge / Chrysler Used Addendum",
    category: "oem",
    family: "traditional_oem",
    description: "Bold OEM-style addendum for Stellantis used inventory.",
    component: UsedAddendumTraditionalOEM,
    defaultBadge: "Certified Pre-Owned",
    ...core,
    supportsMarketTransparency: true,
    supportsCPO: true,
    recommendedPlacement: "outside_window",
    defaultPricingMode: "used_market_value_plus_addendum",
    tags: ["jeep", "ram", "dodge", "chrysler", "oem"],
    suggestedOEMs: ["Jeep", "RAM", "Dodge", "Chrysler"],
  },
  {
    id: "used-oem-kia",
    name: "Kia Used Addendum",
    category: "oem",
    family: "modern_blue",
    description: "Modern addendum for Kia used and certified stores.",
    component: UsedAddendumModernBlue,
    defaultBadge: "Kia Pre-Owned",
    ...core,
    supportsMarketTransparency: true,
    supportsCPO: true,
    recommendedPlacement: "inside_window",
    defaultPricingMode: "used_market_value_plus_addendum",
    tags: ["kia", "oem", "modern"],
    suggestedOEMs: ["Kia"],
  },
  {
    id: "used-oem-lexus",
    name: "Lexus Used Addendum",
    category: "oem",
    family: "luxury_black",
    description: "Luxury addendum for Lexus and L/Certified inventory.",
    component: UsedAddendumLuxuryBlack,
    defaultBadge: "Lexus Pre-Owned",
    ...core,
    supportsMarketTransparency: true,
    supportsCPO: true,
    recommendedPlacement: "inside_window",
    defaultPricingMode: "passport_live_price_only",
    tags: ["lexus", "oem", "luxury"],
    suggestedOEMs: ["Lexus"],
  },
  {
    id: "used-oem-mazda",
    name: "Mazda Used Addendum",
    category: "oem",
    family: "modern_blue",
    description: "Refined modern addendum for Mazda used inventory.",
    component: UsedAddendumModernBlue,
    defaultBadge: "Mazda Pre-Owned",
    ...core,
    supportsMarketTransparency: true,
    supportsCPO: true,
    recommendedPlacement: "inside_window",
    defaultPricingMode: "used_market_value_plus_addendum",
    tags: ["mazda", "oem", "modern"],
    suggestedOEMs: ["Mazda"],
  },
  {
    id: "used-oem-mercedes-benz",
    name: "Mercedes-Benz Used Addendum",
    category: "oem",
    family: "luxury_black",
    description: "Executive premium addendum for Mercedes-Benz pre-owned inventory.",
    component: UsedAddendumLuxuryBlack,
    defaultBadge: "Mercedes-Benz Pre-Owned",
    ...core,
    supportsMarketTransparency: true,
    supportsCPO: true,
    recommendedPlacement: "inside_window",
    defaultPricingMode: "passport_live_price_only",
    tags: ["mercedes-benz", "oem", "luxury"],
    suggestedOEMs: ["Mercedes-Benz"],
  },
  {
    id: "used-oem-nissan",
    name: "Nissan Used Addendum",
    category: "oem",
    family: "modern_blue",
    description: "Flexible addendum for Nissan used and certified inventory.",
    component: UsedAddendumModernBlue,
    defaultBadge: "Nissan Pre-Owned",
    ...core,
    supportsMarketTransparency: true,
    supportsCPO: true,
    recommendedPlacement: "inside_window",
    defaultPricingMode: "used_market_value_plus_addendum",
    tags: ["nissan", "oem", "cpo"],
    suggestedOEMs: ["Nissan"],
  },
  {
    id: "used-oem-subaru",
    name: "Subaru Used Addendum",
    category: "oem",
    family: "traditional_oem",
    description: "Trust-forward OEM-style addendum for Subaru used vehicles.",
    component: UsedAddendumTraditionalOEM,
    defaultBadge: "Subaru Pre-Owned",
    ...core,
    supportsMarketTransparency: true,
    supportsCPO: true,
    recommendedPlacement: "outside_window",
    defaultPricingMode: "used_market_value_plus_addendum",
    tags: ["subaru", "oem", "trust"],
    suggestedOEMs: ["Subaru"],
  },
  {
    id: "used-oem-toyota",
    name: "Toyota Used Addendum",
    category: "oem",
    family: "traditional_oem",
    description: "Traditional addendum for Toyota used and certified inventory.",
    component: UsedAddendumTraditionalOEM,
    defaultBadge: "Toyota Pre-Owned",
    ...core,
    supportsMarketTransparency: true,
    supportsCPO: true,
    recommendedPlacement: "inside_window",
    defaultPricingMode: "used_market_value_plus_addendum",
    tags: ["toyota", "oem", "certified"],
    suggestedOEMs: ["Toyota"],
  },
  {
    id: "used-oem-volkswagen",
    name: "Volkswagen Used Addendum",
    category: "oem",
    family: "modern_blue",
    description: "Clean modern addendum for Volkswagen used inventory.",
    component: UsedAddendumModernBlue,
    defaultBadge: "Volkswagen Pre-Owned",
    ...core,
    supportsMarketTransparency: true,
    supportsCPO: true,
    recommendedPlacement: "inside_window",
    defaultPricingMode: "used_market_value_plus_addendum",
    tags: ["volkswagen", "vw", "oem"],
    suggestedOEMs: ["Volkswagen"],
  },
  {
    id: "used-oem-volvo",
    name: "Volvo Used Addendum",
    category: "oem",
    family: "luxury_black",
    description: "Premium trust-focused addendum for Volvo pre-owned vehicles.",
    component: UsedAddendumLuxuryBlack,
    defaultBadge: "Volvo Pre-Owned",
    ...core,
    supportsMarketTransparency: true,
    supportsCPO: true,
    recommendedPlacement: "inside_window",
    defaultPricingMode: "passport_live_price_only",
    tags: ["volvo", "oem", "premium"],
    suggestedOEMs: ["Volvo"],
  },
];

export const USED_ADDENDUM_CATALOG_BY_ID = Object.fromEntries(USED_ADDENDUM_CATALOG_50.map((template) => [template.id, template]));

export const USED_ADDENDUM_CATEGORIES: UsedAddendumCategory[] = [
  "core",
  "pricing",
  "certification",
  "dealer_value",
  "market_transparency",
  "luxury",
  "specialty",
  "oem",
];
