import type { ComponentType } from "react";
import {
  CheckCircle2, Check, XCircle, AlertTriangle, AlertCircle, Info, BadgeCheck, ShieldCheck,
  Clock, Hourglass, Star, Sparkles, ThumbsUp, Award, Medal, Flag, Ban, CircleDot,
  TrendingUp, TrendingDown, QrCode, Fingerprint, ScanLine, Car, CarFront, Truck, Gauge,
  Fuel, Battery, BatteryCharging, Zap, PlugZap, Cog, Disc, Snowflake, Wind, Thermometer,
  Droplets, Droplet, Key, KeyRound, Lock, Navigation, Compass, MapPin, Camera, Music,
  Bluetooth, Wifi, Smartphone, Sun, Moon, Armchair, Fan, Lightbulb, Eye, Route, Mountain,
  Shield, Layers, Paintbrush, SprayCan, Umbrella, CloudRain, Package, Luggage, Box, Link2,
  Bike, Tent, ShieldPlus, ShieldAlert, HeartHandshake, LifeBuoy, PhoneCall, CalendarClock,
  Infinity as InfinityIcon, FileCheck, Banknote, Gem, Wrench, AirVent, ClipboardCheck,
  CalendarCheck, FileText, FileSignature, Files, FolderOpen, ClipboardList, ScrollText,
  Stamp, Pen, BookOpen, Receipt, Printer, Download, Upload, Search, Copy, Share2,
  ExternalLink, Plus, Minus, X, Menu, Phone, Mail, MessageSquare, Send, Globe, Settings,
  AlertOctagon, BellRing, Waves, FileWarning, RefreshCw, DollarSign, Percent, Tag, Gift,
  Handshake, Users, Volume2, Radio, Timer, CalendarDays, History, Grid3x3, Layers2,
  BadgeDollarSign, PiggyBank, Landmark, CircleDollarSign, Barcode, ArrowRight, ArrowLeft,
  ChevronsRight, Leaf, MinusCircle, PlusCircle, Crosshair, FileClock, FileBadge, IdCard,
  Megaphone, FileX, User, Video, Bookmark,
} from "lucide-react";
import type { AddendumIconCategory, AddendumIconMeta, AddendumIconSource, AddendumIconStatus } from "./iconTypes";
import type { AddendumIconColor } from "./colorTokens";
import {
  PassportBook, PassportShield, PassportBadge, PassportStamp, DigitalPassport,
  VehiclePassportShield, PassportQr, PassportVerified, PassportDocuments, PassportHistory,
  PassportProtection, PassportBenefits, WindowTint, PaintProtectionFilm, WindowSticker,
  AddendumSheet, OilCan, OilChange, FuelNozzle, SteeringWheel, PlaceholderGlyph,
} from "./customIcons";
import {
  PriceLocked, PriceUpdated, DealerInstalled, BumperToBumper, Powertrain, CorrosionShield,
  TireWheel, Windshield, DentDing, TireSwap, BuyersGuide, Hitch, Crossbars, FloorMats,
  WheelLocks, SplashGuards, CargoTray, TonneauCover, BedLiner, RemoteStartFob,
  ChargingCable, ChargingPort, ChargingStation, HybridLeafBolt, PlugInHybrid, Airbag,
  GaugeAlert, HeatedSeats, MudFlaps, RunningBoards, FactoryWarrantyShield, WiperService,
} from "./icons200";

// One definition per icon: the render component AND the manifest row live
// together so the registry and metadata can never drift apart. Artwork for
// custom_required entries is a stand-in — swap the SVG in customIcons.tsx
// (or point `icon` at final art) without touching template code.

export type AddendumIconComponent = ComponentType<{
  size?: number | string;
  strokeWidth?: number | string;
  className?: string;
  "aria-label"?: string;
}>;

export interface AddendumIconDef extends AddendumIconMeta {
  icon: AddendumIconComponent;
}

const ALL_COLORS: AddendumIconColor[] = ["blue", "green", "purple", "orange", "gray", "navy"];

const USE_BY_CATEGORY: Record<AddendumIconCategory, string> = {
  status: "Status rows, verification chips, and result badges",
  passport: "Vehicle Passport trust surfaces and QR touchpoints",
  vehicle: "Spec rows, drivetrain call-outs, and feature highlights",
  accessories: "Addendum line items for installed or optional equipment",
  coverage: "Warranty, protection-plan, and coverage summaries",
  maintenance: "Service records, prep work, and fluid call-outs",
  documents: "Document lists, compliance labels, and packet rows",
  ui: "Buttons, links, and communication actions",
  warnings: "Recall, disclosure, and caution rows",
  pricing_compliance: "Pricing transparency, disclosures, and addendum validation",
  vehicle_status: "Inventory state badges on stickers and admin surfaces",
  ev: "EV and hybrid equipment, charging, and range call-outs",
};

const d = (
  iconId: string,
  name: string,
  category: AddendumIconCategory,
  icon: AddendumIconComponent,
  source: AddendumIconSource,
  defaultColor: AddendumIconColor,
  tags: string[],
  opts: { status?: AddendumIconStatus; description?: string; use?: string; colors?: AddendumIconColor[] } = {},
): AddendumIconDef => ({
  iconId,
  name,
  category,
  icon,
  source,
  defaultColor,
  allowedColors: opts.colors ?? ALL_COLORS,
  tags,
  status: opts.status ?? "ready",
  description: opts.description ?? `${name} icon for ${category} content.`,
  recommendedUse: opts.use ?? USE_BY_CATEGORY[category],
  });

const custom = { status: "custom_required" as const };
const placeholder = { status: "placeholder" as const };

export const ADDENDUM_ICON_DEFS: AddendumIconDef[] = [
  // ── S — Status / indicators ──────────────────────────────────
  d("S001", "Check Circle", "status", CheckCircle2, "lucide", "green", ["check", "verified", "done"]),
  d("S002", "Check", "status", Check, "lucide", "green", ["check", "yes", "included"]),
  d("S003", "X Circle", "status", XCircle, "lucide", "gray", ["no", "excluded", "unavailable"]),
  d("S004", "Alert Triangle", "status", AlertTriangle, "lucide", "orange", ["warning", "caution"]),
  d("S005", "Alert Circle", "status", AlertCircle, "lucide", "orange", ["alert", "attention"]),
  d("S006", "Info", "status", Info, "lucide", "blue", ["info", "note", "detail"]),
  d("S007", "Badge Check", "status", BadgeCheck, "lucide", "green", ["verified", "certified", "badge"]),
  d("S008", "Shield Check", "status", ShieldCheck, "lucide", "green", ["protected", "secure", "verified"]),
  d("S009", "Clock", "status", Clock, "lucide", "blue", ["time", "pending", "schedule"]),
  d("S010", "Hourglass", "status", Hourglass, "lucide", "gray", ["waiting", "processing"]),
  d("S011", "Star", "status", Star, "lucide", "orange", ["rating", "featured", "favorite"]),
  d("S012", "Sparkles", "status", Sparkles, "lucide", "purple", ["new", "highlight", "premium"]),
  d("S013", "Thumbs Up", "status", ThumbsUp, "lucide", "green", ["approved", "recommended"]),
  d("S014", "Award", "status", Award, "lucide", "purple", ["award", "winner", "recognition"]),
  d("S015", "Medal", "status", Medal, "lucide", "orange", ["medal", "achievement", "top"]),
  d("S016", "Flag", "status", Flag, "lucide", "blue", ["flag", "marker", "milestone"]),
  d("S017", "Ban", "status", Ban, "lucide", "gray", ["not included", "prohibited"]),
  d("S018", "Circle Dot", "status", CircleDot, "lucide", "blue", ["active", "selected", "current"]),
  d("S019", "Trending Up", "status", TrendingUp, "lucide", "green", ["value", "increase", "market"]),
  d("S020", "Trending Down", "status", TrendingDown, "lucide", "blue", ["price drop", "decrease"]),

  // ── P — Passport / trust / verification ──────────────────────
  d("P001", "Passport Book", "passport", PassportBook, "custom", "blue", ["passport", "book", "identity"], custom),
  d("P002", "Passport Shield", "passport", PassportShield, "custom", "blue", ["passport", "shield", "trust"], custom),
  d("P003", "Passport Badge", "passport", PassportBadge, "custom", "purple", ["passport", "badge", "certified"], custom),
  d("P004", "Passport Stamp", "passport", PassportStamp, "custom", "navy", ["passport", "stamp", "record"], custom),
  d("P005", "Digital Passport", "passport", DigitalPassport, "custom", "blue", ["passport", "mobile", "digital"], custom),
  d("P006", "Vehicle Passport Shield", "passport", VehiclePassportShield, "custom", "blue", ["passport", "vehicle", "shield"], custom),
  d("P007", "Passport QR", "passport", PassportQr, "custom", "navy", ["passport", "qr", "scan"], custom),
  d("P008", "Passport Verified", "passport", PassportVerified, "custom", "green", ["passport", "verified", "check"], custom),
  d("P009", "Passport Documents", "passport", PassportDocuments, "custom", "blue", ["passport", "documents", "packet"], custom),
  d("P010", "Passport History", "passport", PassportHistory, "custom", "blue", ["passport", "history", "timeline"], custom),
  d("P011", "Passport Protection", "passport", PassportProtection, "custom", "green", ["passport", "protection", "coverage"], custom),
  d("P012", "Passport Benefits", "passport", PassportBenefits, "custom", "purple", ["passport", "benefits", "perks"], custom),
  d("P013", "QR Code", "passport", QrCode, "lucide", "navy", ["qr", "scan", "code"]),
  d("P014", "Fingerprint", "passport", Fingerprint, "lucide", "blue", ["identity", "unique", "vin"]),
  d("P015", "Scan Line", "passport", ScanLine, "lucide", "blue", ["scan", "reader", "capture"]),

  // ── V — Vehicle / performance / drivetrain ───────────────────
  d("V001", "Car", "vehicle", Car, "lucide", "blue", ["car", "vehicle", "sedan"]),
  d("V002", "Car Front", "vehicle", CarFront, "lucide", "blue", ["car", "front", "grille"]),
  d("V003", "Truck", "vehicle", Truck, "lucide", "blue", ["truck", "pickup", "hauling"]),
  d("V004", "Gauge", "vehicle", Gauge, "lucide", "blue", ["speed", "odometer", "performance"]),
  d("V005", "Fuel Pump", "vehicle", Fuel, "lucide", "blue", ["fuel", "gas", "mpg"]),
  d("V006", "Battery", "vehicle", Battery, "lucide", "blue", ["battery", "12v", "power"]),
  d("V007", "Battery Charging", "vehicle", BatteryCharging, "lucide", "green", ["ev", "charging", "hybrid"]),
  d("V008", "EV Bolt", "vehicle", Zap, "lucide", "green", ["electric", "ev", "power"]),
  d("V009", "Charge Plug", "vehicle", PlugZap, "lucide", "green", ["ev", "plug", "charger"]),
  d("V010", "Engine Cog", "vehicle", Cog, "lucide", "blue", ["engine", "mechanical", "powertrain"]),
  d("V011", "Brake Disc", "vehicle", Disc, "lucide", "blue", ["brakes", "rotor", "disc"]),
  d("V012", "Wheel", "vehicle", CircleDot, "lucide", "navy", ["wheel", "tire", "rim"]),
  d("V013", "AWD Snowflake", "vehicle", Snowflake, "lucide", "blue", ["awd", "winter", "traction"]),
  d("V014", "Aerodynamics", "vehicle", Wind, "lucide", "blue", ["aero", "airflow", "spoiler"]),
  d("V015", "Thermometer", "vehicle", Thermometer, "lucide", "orange", ["temperature", "climate", "coolant"]),
  d("V016", "Key", "vehicle", Key, "lucide", "navy", ["key", "keyless", "entry"]),
  d("V017", "Smart Key", "vehicle", KeyRound, "lucide", "navy", ["smart key", "fob", "proximity"]),
  d("V018", "Lock", "vehicle", Lock, "lucide", "navy", ["security", "lock", "anti-theft"]),
  d("V019", "Navigation", "vehicle", Navigation, "lucide", "blue", ["navigation", "gps", "maps"]),
  d("V020", "Compass", "vehicle", Compass, "lucide", "blue", ["compass", "direction", "adventure"]),
  d("V021", "Backup Camera", "vehicle", Camera, "lucide", "blue", ["camera", "backup", "surround view"]),
  d("V022", "Premium Audio", "vehicle", Music, "lucide", "purple", ["audio", "speakers", "sound"]),
  d("V023", "Bluetooth", "vehicle", Bluetooth, "lucide", "blue", ["bluetooth", "wireless", "pairing"]),
  d("V024", "Wi-Fi Hotspot", "vehicle", Wifi, "lucide", "blue", ["wifi", "hotspot", "connectivity"]),
  d("V025", "Smartphone Link", "vehicle", Smartphone, "lucide", "blue", ["carplay", "android auto", "phone"]),
  d("V026", "Sunroof", "vehicle", Sun, "lucide", "orange", ["sunroof", "moonroof", "panoramic"]),
  d("V027", "Moonroof", "vehicle", Moon, "lucide", "navy", ["moonroof", "glass roof"]),
  d("V028", "Seating", "vehicle", Armchair, "lucide", "blue", ["seats", "leather", "comfort"]),
  d("V029", "Climate Fan", "vehicle", Fan, "lucide", "blue", ["climate", "ac", "ventilated"]),
  d("V030", "LED Lighting", "vehicle", Lightbulb, "lucide", "orange", ["led", "headlights", "lighting"]),
  d("V031", "Driver Assist", "vehicle", Eye, "lucide", "blue", ["adas", "monitoring", "blind spot"]),
  d("V032", "Off-Road", "vehicle", Mountain, "lucide", "green", ["offroad", "terrain", "4x4"]),
  d("V033", "Eco Mode", "vehicle", Leaf, "lucide", "green", ["eco", "efficiency", "hybrid"]),
  d("V034", "Steering Wheel", "vehicle", SteeringWheel, "custom", "blue", ["steering", "wheel", "heated wheel"], custom),
  d("V035", "Heated Seats", "vehicle", HeatedSeats, "custom", "blue", ["heated seats", "comfort"], custom),

  // ── A — Accessories / aftermarket ────────────────────────────
  d("A001", "Window Tint", "accessories", WindowTint, "custom", "green", ["tint", "window", "appearance"], custom),
  d("A002", "Paint Protection Film", "accessories", PaintProtectionFilm, "custom", "green", ["ppf", "film", "paint"], custom),
  d("A003", "Ceramic Coating", "accessories", Droplets, "lucide", "green", ["ceramic", "coating", "hydrophobic"]),
  d("A004", "Paint Sealant", "accessories", Paintbrush, "lucide", "green", ["paint", "sealant", "finish"]),
  d("A005", "Undercoating", "accessories", SprayCan, "lucide", "green", ["undercoat", "rust", "spray"]),
  d("A006", "All-Weather Mats", "accessories", CloudRain, "lucide", "green", ["mats", "weather", "floor"]),
  d("A007", "Cargo Package", "accessories", Package, "lucide", "green", ["cargo", "organizer", "trunk"]),
  d("A008", "Cargo Cover", "accessories", Box, "lucide", "green", ["cargo", "cover", "privacy"]),
  d("A009", "Luggage Carrier", "accessories", Luggage, "lucide", "green", ["luggage", "carrier", "travel"]),
  d("A010", "Roof Rack", "accessories", Crossbars, "custom", "green", ["roof rack", "crossbars"], custom),
  d("A011", "Trailer Hitch", "accessories", Link2, "lucide", "green", ["hitch", "towing", "trailer"]),
  d("A012", "Bike Rack", "accessories", Bike, "lucide", "green", ["bike", "rack", "carrier"]),
  d("A013", "Roof Tent Ready", "accessories", Tent, "lucide", "green", ["overland", "tent", "camping"]),
  d("A014", "Mud Flaps", "accessories", MudFlaps, "custom", "green", ["mud flaps", "splash guards"], custom),
  d("A015", "Bed Liner", "accessories", BedLiner, "custom", "green", ["bed liner", "truck bed"], custom),
  d("A016", "Running Boards", "accessories", RunningBoards, "custom", "green", ["running boards", "steps"], custom),
  d("A017", "Tonneau Cover", "accessories", TonneauCover, "custom", "green", ["tonneau", "bed cover"], custom),
  d("A018", "Wheel Locks", "accessories", Lock, "lucide", "green", ["wheel locks", "security"]),
  d("A019", "Remote Start", "accessories", Radio, "lucide", "green", ["remote start", "convenience"]),
  d("A020", "Alarm System", "accessories", BellRing, "lucide", "green", ["alarm", "security", "anti-theft"]),
  d("A021", "Dash Camera", "accessories", Camera, "lucide", "green", ["dash cam", "recording"]),
  d("A022", "Splash Guards", "accessories", Droplet, "lucide", "green", ["splash", "guards"]),
  d("A023", "Door Edge Guards", "accessories", Shield, "lucide", "green", ["door", "edge", "guards"]),
  d("A024", "Body Side Molding", "accessories", Layers, "lucide", "green", ["molding", "body side"]),
  d("A025", "Nitrogen Fill", "accessories", Wind, "lucide", "green", ["nitrogen", "tires"]),
  d("A026", "Interior Protection", "accessories", Armchair, "lucide", "green", ["interior", "fabric", "leather care"]),
  d("A027", "Grille Guard", "accessories", Grid3x3, "lucide", "green", ["grille", "guard", "brush"]),
  d("A028", "Accessory Bundle", "accessories", Gift, "lucide", "purple", ["bundle", "package", "value"]),
  d("A029", "Dealer Installed", "accessories", Wrench, "lucide", "green", ["dealer installed", "equipment"]),
  d("A030", "Optional Add-On", "accessories", Plus, "lucide", "gray", ["optional", "available", "add-on"]),
  d("A031", "Not Included In Total", "accessories", Minus, "lucide", "gray", ["not included", "excluded", "pricing"]),
  d("A032", "Appearance Package", "accessories", Sparkles, "lucide", "purple", ["appearance", "styling"]),

  // ── C — Coverage / warranty / protection ─────────────────────
  d("C001", "Warranty Shield", "coverage", Shield, "lucide", "blue", ["warranty", "coverage", "protection"]),
  d("C002", "Coverage Verified", "coverage", ShieldCheck, "lucide", "green", ["warranty", "verified", "active"]),
  d("C003", "Extended Coverage", "coverage", ShieldPlus, "lucide", "purple", ["extended", "warranty", "vsc"]),
  d("C004", "Coverage Alert", "coverage", ShieldAlert, "lucide", "orange", ["expiring", "coverage", "attention"]),
  d("C005", "Factory Warranty", "coverage", FactoryWarrantyShield, "custom", "green", ["factory", "warranty", "oem"], custom),
  d("C006", "Roadside Assistance", "coverage", LifeBuoy, "lucide", "blue", ["roadside", "assistance", "towing"]),
  d("C007", "Assistance Hotline", "coverage", PhoneCall, "lucide", "blue", ["hotline", "support", "24/7"]),
  d("C008", "Coverage Term", "coverage", CalendarClock, "lucide", "blue", ["term", "months", "expiration"]),
  d("C009", "Unlimited Miles", "coverage", InfinityIcon, "lucide", "green", ["unlimited", "miles"]),
  d("C010", "Service Contract", "coverage", FileCheck, "lucide", "blue", ["contract", "vsc", "agreement"]),
  d("C011", "Deductible", "coverage", Banknote, "lucide", "navy", ["deductible", "cost", "claim"]),
  d("C012", "Premium Protection", "coverage", Gem, "lucide", "purple", ["premium", "tier", "top"]),
  d("C013", "Corrosion Coverage", "coverage", Umbrella, "lucide", "blue", ["corrosion", "rust", "perforation"]),
  d("C014", "Customer Care", "coverage", HeartHandshake, "lucide", "green", ["care", "goodwill", "support"]),
  d("C015", "Transferable", "coverage", RefreshCw, "lucide", "blue", ["transferable", "second owner"]),
  d("C016", "Certified Coverage", "coverage", BadgeCheck, "lucide", "purple", ["cpo", "certified", "program"]),

  // ── M — Maintenance / service / fluids ───────────────────────
  d("M001", "Oil Service", "maintenance", Droplet, "lucide", "orange", ["oil", "change", "fluid"]),
  d("M002", "Fuel System", "maintenance", Fuel, "lucide", "orange", ["fuel", "system", "injector"]),
  d("M003", "Wrench", "maintenance", Wrench, "lucide", "blue", ["repair", "service", "mechanical"]),
  d("M004", "Multi-Point Inspection", "maintenance", ClipboardCheck, "lucide", "green", ["inspection", "multi-point", "prep"]),
  d("M005", "Scheduled Service", "maintenance", CalendarCheck, "lucide", "blue", ["scheduled", "maintenance", "interval"]),
  d("M006", "Cabin Air Filter", "maintenance", AirVent, "lucide", "blue", ["filter", "cabin", "air"]),
  d("M007", "Battery Service", "maintenance", Battery, "lucide", "orange", ["battery", "test", "replace"]),
  d("M008", "Brake Service", "maintenance", Disc, "lucide", "orange", ["brakes", "pads", "rotors"]),
  d("M009", "Tire Rotation", "maintenance", RefreshCw, "lucide", "blue", ["tires", "rotation", "balance"]),
  d("M010", "Alignment", "maintenance", Route, "lucide", "blue", ["alignment", "steering"]),
  d("M011", "Coolant Service", "maintenance", Thermometer, "lucide", "orange", ["coolant", "flush", "radiator"]),
  d("M012", "Detail Service", "maintenance", Sparkles, "lucide", "purple", ["detail", "clean", "recondition"]),
  d("M013", "Car Wash", "maintenance", SprayCan, "lucide", "blue", ["wash", "exterior", "clean"]),
  d("M014", "Wiper Service", "maintenance", WiperService, "custom", "blue", ["wipers", "blades", "visibility"], custom),
  d("M015", "Service Timer", "maintenance", Timer, "lucide", "blue", ["due", "interval", "reminder"]),
  d("M016", "Reconditioning", "maintenance", History, "lucide", "green", ["recon", "get ready", "restored"]),
  d("M017", "Oil Can", "maintenance", OilCan, "custom", "blue", ["oil can", "oil service", "lubrication"], custom),
  d("M018", "Oil Change Interval", "maintenance", OilChange, "custom", "blue", ["oil change", "interval", "maintenance"], custom),
  d("M019", "Fuel Nozzle", "maintenance", FuelNozzle, "custom", "blue", ["fuel nozzle", "fuel type", "refill"], custom),

  // ── D — Documents / compliance ───────────────────────────────
  d("D001", "Document", "documents", FileText, "lucide", "navy", ["document", "file", "page"]),
  d("D002", "Verified Document", "documents", FileCheck, "lucide", "green", ["verified", "approved", "document"]),
  d("D003", "Signature Document", "documents", FileSignature, "lucide", "navy", ["signature", "esign", "signed"]),
  d("D004", "Document Set", "documents", Files, "lucide", "navy", ["packet", "documents", "set"]),
  d("D005", "Document Folder", "documents", FolderOpen, "lucide", "navy", ["folder", "records", "archive"]),
  d("D006", "Checklist", "documents", ClipboardList, "lucide", "blue", ["checklist", "items", "tasks"]),
  d("D007", "Disclosure", "documents", ScrollText, "lucide", "navy", ["disclosure", "terms", "legal"]),
  d("D008", "Official Stamp", "documents", Stamp, "lucide", "navy", ["stamp", "official", "notarized"]),
  d("D009", "Signature Pen", "documents", Pen, "lucide", "navy", ["pen", "sign", "initial"]),
  d("D010", "Owner Manual", "documents", BookOpen, "lucide", "blue", ["manual", "booklet", "guide"]),
  d("D011", "Receipt", "documents", Receipt, "lucide", "navy", ["receipt", "invoice", "purchase"]),
  d("D012", "Window Sticker", "documents", WindowSticker, "custom", "blue", ["window sticker", "monroney", "label"], custom),
  d("D013", "Addendum", "documents", AddendumSheet, "custom", "blue", ["addendum", "supplemental", "sticker"], custom),
  d("D014", "Buyers Guide", "documents", BuyersGuide, "custom", "navy", ["buyers guide", "ftc", "as-is"], custom),
  d("D015", "FTC Compliant", "documents", ShieldCheck, "lucide", "green", ["ftc", "compliant", "regulation"], { description: "Alias of PR201 FTC Compliant — same artwork, documents-range ID.", use: "Use PR201 for new work; D015 exists for documents-range callers" }),
  d("D016", "Title Record", "documents", FileWarning, "lucide", "navy", ["title", "brand", "record"], placeholder),
  d("D017", "Barcode", "documents", Barcode, "lucide", "navy", ["barcode", "vin", "scan"]),

  // ── U — UI / actions / communication ─────────────────────────
  d("U001", "Search", "ui", Search, "lucide", "gray", ["search", "find", "lookup"]),
  d("U002", "Copy", "ui", Copy, "lucide", "gray", ["copy", "duplicate", "clipboard"]),
  d("U003", "Share", "ui", Share2, "lucide", "blue", ["share", "send", "social"]),
  d("U004", "External Link", "ui", ExternalLink, "lucide", "blue", ["link", "external", "open"]),
  d("U005", "Add", "ui", Plus, "lucide", "blue", ["add", "new", "create"]),
  d("U006", "Remove", "ui", X, "lucide", "gray", ["remove", "close", "dismiss"]),
  d("U007", "Menu", "ui", Menu, "lucide", "navy", ["menu", "navigation", "list"]),
  d("U008", "Phone", "ui", Phone, "lucide", "blue", ["call", "phone", "contact"]),
  d("U009", "Email", "ui", Mail, "lucide", "blue", ["email", "message", "contact"]),
  d("U010", "Message", "ui", MessageSquare, "lucide", "blue", ["chat", "text", "sms"]),
  d("U011", "Send", "ui", Send, "lucide", "blue", ["send", "submit", "deliver"]),
  d("U012", "Website", "ui", Globe, "lucide", "blue", ["website", "online", "web"]),
  d("U013", "Settings", "ui", Settings, "lucide", "gray", ["settings", "configure", "admin"]),
  d("U014", "Download", "ui", Download, "lucide", "blue", ["download", "save", "export"]),
  d("U015", "Upload", "ui", Upload, "lucide", "blue", ["upload", "attach", "import"]),
  d("U016", "Print", "ui", Printer, "lucide", "navy", ["print", "paper", "output"]),
  d("U017", "Price Tag", "ui", Tag, "lucide", "green", ["price", "tag", "label"]),
  d("U018", "Dollar", "ui", DollarSign, "lucide", "green", ["price", "dollar", "payment"]),
  d("U019", "Percent", "ui", Percent, "lucide", "green", ["apr", "percent", "rate"]),
  d("U020", "Handshake", "ui", Handshake, "lucide", "green", ["deal", "agreement", "close"]),
  d("U021", "Team", "ui", Users, "lucide", "blue", ["team", "staff", "people"]),
  d("U022", "Announcement", "ui", Volume2, "lucide", "orange", ["announce", "promo", "offer"]),
  d("U023", "Calendar", "ui", CalendarDays, "lucide", "blue", ["calendar", "date", "appointment"]),
  d("U024", "Layers", "ui", Layers2, "lucide", "gray", ["layers", "stack", "templates"]),
  d("U025", "Savings Tag", "ui", BadgeDollarSign, "lucide", "green", ["savings", "fuel savings", "value tag"]),
  d("U026", "Savings", "ui", PiggyBank, "lucide", "green", ["savings", "budget", "piggy bank"]),
  d("U027", "Financing", "ui", Landmark, "lucide", "blue", ["financing", "bank", "lender"]),
  d("U028", "Price Circle", "ui", CircleDollarSign, "lucide", "green", ["price", "cost", "dollar"]),
  d("U029", "Arrow Right", "ui", ArrowRight, "lucide", "blue", ["arrow", "next", "forward"]),
  d("U030", "Arrow Left", "ui", ArrowLeft, "lucide", "blue", ["arrow", "back", "previous"]),
  d("U031", "Chevrons Right", "ui", ChevronsRight, "lucide", "blue", ["chevrons", "more", "continue"]),

  // ── W — Warnings / alerts / recall ───────────────────────────
  d("W001", "Open Recall", "warnings", AlertOctagon, "lucide", "orange", ["recall", "open", "nhtsa"]),
  d("W002", "Stop Sale", "warnings", Ban, "lucide", "orange", ["stop sale", "do not drive"]),
  d("W003", "Recall Notice", "warnings", BellRing, "lucide", "orange", ["recall", "notice", "campaign"]),
  d("W004", "Caution", "warnings", AlertTriangle, "lucide", "orange", ["caution", "warning"]),
  d("W005", "Flood History", "warnings", Waves, "lucide", "orange", ["flood", "water", "damage"]),
  d("W006", "Branded Title", "warnings", FileWarning, "lucide", "orange", ["salvage", "branded", "title"]),
  d("W007", "Odometer Alert", "warnings", Gauge, "lucide", "orange", ["odometer", "rollback", "discrepancy"]),
  d("W008", "Airbag Recall", "warnings", Airbag, "custom", "orange", ["airbag", "takata", "recall"], custom),
  d("W009", "Inspection Required", "warnings", ClipboardCheck, "lucide", "orange", ["inspection", "required", "state"]),
  d("W010", "Time Sensitive", "warnings", Timer, "lucide", "orange", ["deadline", "expiring", "urgent"]),

  // ══ 200-series — "Missing Addendum Icons" reference sheet ══════

  // ── PR — Pricing / Compliance ────────────────────────────────
  d("PR201", "FTC Compliant", "pricing_compliance", ShieldCheck, "lucide", "blue", ["ftc", "compliance", "pricing", "disclosure", "legal"], { use: "Compliance footer, pricing transparency, addendum validation" }),
  d("PR202", "Price Locked", "pricing_compliance", PriceLocked, "custom", "blue", ["price", "locked", "guaranteed"], custom),
  d("PR203", "Price Updated", "pricing_compliance", PriceUpdated, "custom", "blue", ["price", "updated", "refreshed"], custom),
  d("PR204", "Disclosure", "pricing_compliance", ScrollText, "lucide", "blue", ["disclosure", "terms", "legal"]),
  d("PR205", "Included in Price", "pricing_compliance", CheckCircle2, "lucide", "green", ["included", "in price", "no charge"]),
  d("PR206", "Not Included", "pricing_compliance", MinusCircle, "lucide", "blue", ["not included", "excluded", "extra"]),
  d("PR207", "Dealer Installed", "pricing_compliance", DealerInstalled, "custom", "blue", ["dealer installed", "equipment", "addendum"], custom),
  d("PR208", "Optional Item", "pricing_compliance", Star, "lucide", "purple", ["optional", "upgrade", "available"]),

  // ── ST — Vehicle Status ──────────────────────────────────────
  d("ST201", "New", "vehicle_status", Sparkles, "lucide", "blue", ["new", "brand new", "factory"]),
  d("ST202", "Used", "vehicle_status", Car, "lucide", "blue", ["used", "pre-owned"]),
  d("ST203", "CPO", "vehicle_status", BadgeCheck, "lucide", "green", ["cpo", "certified", "pre-owned"]),
  d("ST204", "Demo", "vehicle_status", Tag, "lucide", "blue", ["demo", "demonstrator", "loaner"]),
  d("ST205", "Loaner", "vehicle_status", User, "lucide", "blue", ["loaner", "courtesy", "service"]),
  d("ST206", "In Transit", "vehicle_status", Truck, "lucide", "blue", ["in transit", "arriving", "incoming"]),
  d("ST207", "Sold", "vehicle_status", Handshake, "lucide", "orange", ["sold", "delivered", "closed"]),
  d("ST208", "Reserved", "vehicle_status", Bookmark, "lucide", "purple", ["reserved", "hold", "deposit"]),
  d("ST209", "Available", "vehicle_status", CheckCircle2, "lucide", "green", ["available", "in stock", "ready"]),

  // ── WC — Warranty / Coverage ─────────────────────────────────
  d("WC201", "Bumper-to-Bumper", "coverage", BumperToBumper, "custom", "green", ["bumper to bumper", "basic", "comprehensive"], custom),
  d("WC202", "Powertrain", "coverage", Powertrain, "custom", "green", ["powertrain", "engine", "transmission"], custom),
  d("WC203", "Corrosion", "coverage", CorrosionShield, "custom", "green", ["corrosion", "rust", "perforation"], custom),
  d("WC204", "Emissions", "coverage", Leaf, "lucide", "green", ["emissions", "epa", "federal"]),
  d("WC205", "Roadside", "coverage", LifeBuoy, "lucide", "green", ["roadside", "towing", "assistance"]),
  d("WC206", "Maintenance Plan", "coverage", CalendarCheck, "lucide", "green", ["maintenance", "plan", "prepaid"]),
  d("WC207", "Tire & Wheel", "coverage", TireWheel, "custom", "green", ["tire", "wheel", "road hazard"], custom),
  d("WC208", "Key Replacement", "coverage", Key, "lucide", "green", ["key", "replacement", "fob"]),
  d("WC209", "Windshield", "coverage", Windshield, "custom", "green", ["windshield", "glass", "chip"], custom),
  d("WC210", "Dent / Ding", "coverage", DentDing, "custom", "green", ["dent", "ding", "paintless repair"], custom),

  // ── SR — Service / Recon ─────────────────────────────────────
  d("SR201", "Safety Inspection", "maintenance", ClipboardCheck, "lucide", "blue", ["safety", "inspection", "state"]),
  d("SR202", "Oil Service", "maintenance", OilCan, "custom", "blue", ["oil", "service", "change"], custom),
  d("SR203", "Brake Service", "maintenance", Disc, "lucide", "blue", ["brakes", "pads", "rotors"]),
  d("SR204", "Tire Replacement", "maintenance", TireSwap, "custom", "blue", ["tires", "replacement", "new tires"], custom),
  d("SR205", "Alignment", "maintenance", Crosshair, "lucide", "blue", ["alignment", "steering", "suspension"]),
  d("SR206", "Battery Test", "maintenance", BatteryCharging, "lucide", "blue", ["battery", "test", "charge"]),
  d("SR207", "Detail Complete", "maintenance", Sparkles, "lucide", "green", ["detail", "clean", "complete"]),
  d("SR208", "Recall Checked", "maintenance", BadgeCheck, "lucide", "green", ["recall", "checked", "verified"]),
  d("SR209", "Recall Open", "maintenance", BellRing, "lucide", "orange", ["recall", "open", "outstanding"]),
  d("SR210", "No Recall", "maintenance", ShieldCheck, "lucide", "green", ["no recall", "clear", "nhtsa"]),

  // ── DC — Documents ───────────────────────────────────────────
  d("DC201", "Buyer's Guide", "documents", BuyersGuide, "custom", "blue", ["buyers guide", "ftc", "as-is", "warranty"], custom),
  d("DC202", "Vehicle History", "documents", FileClock, "lucide", "blue", ["history", "carfax", "autocheck", "report"]),
  d("DC203", "Title", "documents", FileBadge, "lucide", "blue", ["title", "certificate", "ownership"]),
  d("DC204", "Registration", "documents", IdCard, "lucide", "blue", ["registration", "dmv", "plates"]),
  d("DC205", "Payoff", "documents", Banknote, "lucide", "blue", ["payoff", "lien", "balance"]),
  d("DC206", "Insurance", "documents", Shield, "lucide", "blue", ["insurance", "proof", "coverage"]),
  d("DC207", "Window Sticker", "documents", WindowSticker, "custom", "blue", ["window sticker", "monroney", "label"], custom),
  d("DC208", "Purchase Order", "documents", Receipt, "lucide", "blue", ["purchase order", "buyers order", "deal"]),

  // ── CA — Customer Actions ────────────────────────────────────
  d("CA201", "Scan QR", "ui", QrCode, "lucide", "purple", ["scan", "qr", "code"]),
  d("CA202", "Upload Photos", "ui", Camera, "lucide", "purple", ["upload", "photos", "trade"]),
  d("CA203", "Sign Document", "ui", FileSignature, "lucide", "purple", ["sign", "esign", "signature"]),
  d("CA204", "Schedule Visit", "ui", CalendarDays, "lucide", "purple", ["schedule", "visit", "appointment"]),
  d("CA205", "Call", "ui", Phone, "lucide", "purple", ["call", "phone", "sales"]),
  d("CA206", "Text", "ui", MessageSquare, "lucide", "purple", ["text", "sms", "message"]),
  d("CA207", "Email", "ui", Mail, "lucide", "purple", ["email", "contact", "message"]),
  d("CA208", "Get Directions", "ui", MapPin, "lucide", "purple", ["directions", "map", "dealership"]),

  // ── AX — Accessories ─────────────────────────────────────────
  d("AX201", "Hitch", "accessories", Hitch, "custom", "purple", ["hitch", "towing", "ball mount"], custom),
  d("AX202", "Crossbars", "accessories", Crossbars, "custom", "purple", ["crossbars", "roof rack", "rails"], custom),
  d("AX203", "Floor Mats", "accessories", FloorMats, "custom", "purple", ["floor mats", "all weather", "carpet"], custom),
  d("AX204", "Tint", "accessories", WindowTint, "custom", "purple", ["tint", "window", "film"], custom),
  d("AX205", "PPF", "accessories", PaintProtectionFilm, "custom", "purple", ["ppf", "paint protection", "film"], custom),
  d("AX206", "Ceramic Coating", "accessories", Droplets, "lucide", "purple", ["ceramic", "coating", "hydrophobic"]),
  d("AX207", "Wheel Locks", "accessories", WheelLocks, "custom", "purple", ["wheel locks", "lug", "security"], custom),
  d("AX208", "Splash Guards", "accessories", SplashGuards, "custom", "purple", ["splash guards", "mud flaps"], custom),
  d("AX209", "Cargo Tray", "accessories", CargoTray, "custom", "purple", ["cargo tray", "trunk", "liner"], custom),
  d("AX210", "Tonneau Cover", "accessories", TonneauCover, "custom", "purple", ["tonneau", "bed cover", "truck"], custom),
  d("AX211", "Bed Liner", "accessories", BedLiner, "custom", "purple", ["bed liner", "spray in", "truck bed"], custom),
  d("AX212", "Remote Start", "accessories", RemoteStartFob, "custom", "purple", ["remote start", "fob", "convenience"], custom),
  d("AX213", "Dash Cam", "accessories", Video, "lucide", "purple", ["dash cam", "camera", "recording"]),
  d("AX214", "Accessory / Add-On", "accessories", PlusCircle, "lucide", "purple", ["accessory", "add-on", "extra"]),

  // ── EV — EV / Hybrid ─────────────────────────────────────────
  d("EV201", "EV Battery", "ev", BatteryCharging, "lucide", "green", ["ev", "battery", "high voltage"]),
  d("EV202", "Charging Cable", "ev", ChargingCable, "custom", "green", ["charging", "cable", "cord"], custom),
  d("EV203", "Charging Port", "ev", ChargingPort, "custom", "green", ["charging", "port", "connector"], custom),
  d("EV204", "Charging Station", "ev", ChargingStation, "custom", "green", ["charging", "station", "level 2"], custom),
  d("EV205", "Hybrid", "ev", HybridLeafBolt, "custom", "green", ["hybrid", "electric", "gas"], custom),
  d("EV206", "Plug-In Hybrid", "ev", PlugInHybrid, "custom", "green", ["phev", "plug-in", "hybrid"], custom),
  d("EV207", "EV Range", "ev", Gauge, "lucide", "blue", ["range", "miles", "battery"]),

  // ── WA — Warnings ────────────────────────────────────────────
  d("WA201", "Recall", "warnings", AlertTriangle, "lucide", "orange", ["recall", "warning", "safety"]),
  d("WA202", "Airbag", "warnings", Airbag, "custom", "orange", ["airbag", "takata", "srs"], custom),
  d("WA203", "Mileage Discrepancy", "warnings", GaugeAlert, "custom", "orange", ["mileage", "odometer", "discrepancy"], custom),
  d("WA204", "Title Issue", "warnings", FileWarning, "lucide", "orange", ["title", "brand", "issue"]),
  d("WA205", "Open Campaign", "warnings", Megaphone, "lucide", "orange", ["campaign", "service", "open"]),
  d("WA206", "Document Missing", "warnings", FileX, "lucide", "orange", ["document", "missing", "pending"]),
  d("WA207", "Pending Verification", "warnings", Hourglass, "lucide", "orange", ["pending", "verification", "review"]),
];

export const ADDENDUM_ICON_METADATA: AddendumIconMeta[] = ADDENDUM_ICON_DEFS.map((def) => {
  const { icon: _icon, ...meta } = def;
  return meta;
});
