import { useCallback, useState } from "react";
import { supabase } from "@/integrations/supabase/client";

// One client seam onto factory-sticker-orchestrate. Every entry point —
// the nightly ingest's record, the Vehicle File card, and the Window
// Sticker Studio — drives the same server actions, so a sticker created
// automatically and one regenerated by hand go through identical
// selection, validation, versioning and publication logic.

export const REGENERATION_REASONS = [
  { code: "vehicle_information_corrected", label: "Vehicle information was corrected" },
  { code: "additional_source_data_available", label: "Additional NeoVIN information is now available" },
  { code: "options_or_packages_corrected", label: "Options or packages were corrected" },
  { code: "msrp_corrected", label: "MSRP information was corrected" },
  { code: "wrong_template_selected", label: "Wrong OEM template was selected" },
  { code: "pdf_or_layout_problem", label: "PDF or layout problem" },
  { code: "qr_or_passport_link_changed", label: "QR code or Passport link changed" },
  { code: "other", label: "Other" },
] as const;

export type RegenerationReasonCode = (typeof REGENERATION_REASONS)[number]["code"];

export interface StickerVersion {
  id: string;
  version: number;
  status: string;
  pdf_url: string | null;
  published_at: string | null;
  created_at: string | null;
  updated_at: string | null;
  superseded_by: string | null;
  generated_by: string;
  generated_by_user_id: string | null;
  reason_code: string | null;
  reason_notes: string | null;
  data_source: string | null;
  template_key: string | null;
  template_family_id: string | null;
  template_version: string | null;
  renderer_version: string | null;
  content_hash: string | null;
  reconciliation_status: string | null;
}

export interface DocumentAssets {
  document_id: string;
  version: number | null;
  status: string | null;
  pdf_url: string | null;
  preview_url: string | null;
  content_hash: string | null;
}

interface InvokeArgs {
  action: string;
  tenantId: string;
  vehicleId?: string;
  vin?: string;
  extra?: Record<string, unknown>;
}

async function invokeOrchestrator<T>({ action, tenantId, vehicleId, vin, extra }: InvokeArgs): Promise<T> {
  const { data, error } = await supabase.functions.invoke("factory-sticker-orchestrate", {
    body: {
      action,
      tenant_id: tenantId,
      ...(vehicleId ? { vehicle_id: vehicleId } : {}),
      ...(vin ? { vin } : {}),
      app_base: typeof window !== "undefined" ? window.location.origin : undefined,
      ...(extra || {}),
    },
  });
  const payload = (data || {}) as Record<string, unknown>;
  if (error || payload.success !== true) {
    throw new Error(String(error?.message || payload.error || "request failed"));
  }
  return payload as T;
}

export interface RegenerateArgs {
  tenantId: string;
  vehicleId: string;
  reasonCode: RegenerationReasonCode;
  reasonNotes?: string | null;
  /** "reuse" replays the stored provider response at no charge. */
  dataSource: "reuse" | "refresh";
}

export function useWindowSticker() {
  const [busy, setBusy] = useState(false);

  const regenerate = useCallback(async (args: RegenerateArgs) => {
    setBusy(true);
    try {
      return await invokeOrchestrator<{
        status?: string; version?: number; document_id?: string;
        source_refresh?: { ok: boolean; detail: string | null };
      }>({
        action: "regenerate",
        tenantId: args.tenantId,
        vehicleId: args.vehicleId,
        extra: {
          reason_code: args.reasonCode,
          reason_notes: args.reasonNotes || null,
          data_source: args.dataSource,
        },
      });
    } finally {
      setBusy(false);
    }
  }, []);

  const versionHistory = useCallback(async (tenantId: string, vehicleId: string) => {
    const res = await invokeOrchestrator<{ versions: StickerVersion[]; current_document_id: string | null }>({
      action: "version_history", tenantId, vehicleId,
    });
    return res;
  }, []);

  const documentAssets = useCallback(async (tenantId: string, vehicleId: string, documentId: string) => {
    return await invokeOrchestrator<DocumentAssets>({
      action: "document_assets", tenantId, vehicleId, extra: { document_id: documentId },
    });
  }, []);

  const restoreVersion = useCallback(async (tenantId: string, vehicleId: string, documentId: string) => {
    setBusy(true);
    try {
      return await invokeOrchestrator<{ document_id: string; status: string }>({
        action: "restore_version", tenantId, vehicleId, extra: { document_id: documentId },
      });
    } finally {
      setBusy(false);
    }
  }, []);

  const approvePublish = useCallback(async (tenantId: string, vehicleId: string) => {
    setBusy(true);
    try {
      return await invokeOrchestrator<{ document_id: string; status: string }>({
        action: "approve_publish", tenantId, vehicleId,
      });
    } finally {
      setBusy(false);
    }
  }, []);

  const unpublish = useCallback(async (tenantId: string, vehicleId: string) => {
    setBusy(true);
    try {
      return await invokeOrchestrator<{ status: string }>({
        action: "unpublish", tenantId, vehicleId,
      });
    } finally {
      setBusy(false);
    }
  }, []);

  const generate = useCallback(async (tenantId: string, vehicleId?: string, vin?: string) => {
    setBusy(true);
    try {
      return await invokeOrchestrator<{ status?: string; record_id?: string; document_id?: string }>({
        action: "orchestrate", tenantId, vehicleId, vin,
      });
    } finally {
      setBusy(false);
    }
  }, []);

  return { busy, regenerate, versionHistory, documentAssets, restoreVersion, approvePublish, unpublish, generate };
}
